/* =====================================================================
   AZ-900 Study Hub — comprehensive scenario question bank
   Style modelled on real AZ-900 practice exams (long real-world
   scenarios, 4 options, single best answer). Covers every topic so
   this can serve as a complete practice resource.

   Loaded BEFORE js/data.js, which picks these up as AZ.QUESTIONS.
   Each item: { cat, topic, q, options[], answer(index), explain }
   ===================================================================== */
window.AZ_QUESTIONS = [

  /* ===================== CLOUD CONCEPTS ===================== */

  /* --- Cloud Models (c_models) --- */
  { cat: "cloud", topic: "c_models", q: "Your organization is deploying a web application to Azure. The application must be accessible to users worldwide over the internet without requiring a VPN connection or private network configuration. Which cloud deployment model best describes this accessibility requirement?", options: ["Public cloud", "Private cloud", "Community cloud", "Hybrid cloud"], answer: 0, explain: "Public cloud delivers services over the public internet, shared (multi-tenant) and accessible to anyone with credentials — ideal for globally accessible apps with no private networking requirement." },
  { cat: "cloud", topic: "c_models", q: "A manufacturing company has servers running in their on-premises datacenter, virtual machines running in AWS, and resources deployed in Azure. The IT director wants to use Azure management tools, apply Azure policies, and view all resources through a single control plane regardless of where they are physically located. Which Azure service should the company implement?", options: ["Azure Monitor", "Azure Arc", "Azure Resource Manager", "Microsoft Defender for Cloud"], answer: 1, explain: "Azure Arc extends Azure management and governance (policies, RBAC, a single control plane) to on-premises, multi-cloud, and edge resources." },
  { cat: "cloud", topic: "c_models", q: "A hospital must keep patient records on-premises to meet strict data-residency regulations, but wants to use the cloud's scalability for running analytics during peak periods. Which deployment model fits this need?", options: ["Public cloud", "Private cloud", "Hybrid cloud", "Multi-cloud"], answer: 2, explain: "Hybrid cloud combines on-premises (private) infrastructure with public cloud, letting sensitive data stay on-prem while bursting to the cloud for extra capacity." },
  { cat: "cloud", topic: "c_models", q: "A company wants to use services from both Microsoft Azure and Amazon Web Services at the same time to avoid being locked into a single provider. What is this approach called?", options: ["Hybrid cloud", "Multi-cloud", "Private cloud", "Community cloud"], answer: 1, explain: "Using more than one public cloud provider simultaneously is multi-cloud, often chosen to avoid vendor lock-in or use best-of-breed services." },
  { cat: "cloud", topic: "c_models", q: "An organization requires complete control over its hardware and security and is willing to fund and maintain its own dedicated infrastructure used exclusively by the company. Which deployment model should they choose?", options: ["Public cloud", "Private cloud", "Hybrid cloud", "Multi-cloud"], answer: 1, explain: "A private cloud is used exclusively by one organization, offering the most control but requiring CapEx and ongoing maintenance." },
  { cat: "cloud", topic: "c_models", q: "Which characteristic is unique to the public cloud model?", options: ["Hardware is dedicated to a single organization", "It is always hosted in the customer's own datacenter", "Resources are multi-tenant and delivered over the internet by a third party", "It requires a large upfront capital investment"], answer: 2, explain: "Public cloud is multi-tenant, owned/operated by a third-party provider, and delivered over the internet with no CapEx." },
  { cat: "cloud", topic: "c_models", q: "A retail company wants to run VMware-based workloads natively in Azure without re-architecting them. Which Azure offering supports this?", options: ["Azure Arc", "Azure VMware Solution", "Azure Migrate", "Azure Kubernetes Service"], answer: 1, explain: "Azure VMware Solution lets you run native VMware environments directly on Azure infrastructure." },
  { cat: "cloud", topic: "c_models", q: "During seasonal demand, a company temporarily uses public cloud capacity in addition to its private datacenter, then scales back afterward. What is this practice commonly called?", options: ["Cloud bursting", "Geo-replication", "Vertical scaling", "Lift and shift"], answer: 0, explain: "Cloud bursting is a hybrid-cloud pattern where workloads 'burst' into the public cloud for extra capacity during peaks." },

  /* --- Cost Model CapEx/OpEx (c_cost) --- */
  { cat: "cloud", topic: "c_cost", q: "A retail company currently manages its own data center with physical servers that often sit idle during off-peak hours. The company pays fixed costs for hardware, cooling, and maintenance regardless of actual usage. They are considering moving to Azure to optimize their IT spending. Which characteristic of cloud computing would most directly address their concern about paying for unused capacity?", options: ["High availability", "Geo-distribution", "Disaster recovery", "Pay-as-you-go pricing"], answer: 3, explain: "Pay-as-you-go (consumption-based) pricing means you only pay for the resources you actually use, eliminating the cost of idle, over-provisioned capacity." },
  { cat: "cloud", topic: "c_cost", q: "A startup with very little upfront capital needs to launch a product quickly and wants to avoid buying any physical servers. Which expenditure model does moving to the cloud provide?", options: ["Capital expenditure (CapEx)", "Operational expenditure (OpEx)", "Fixed depreciation", "Amortized hardware cost"], answer: 1, explain: "The cloud shifts spending to OpEx — ongoing, pay-as-you-go operational costs — instead of large upfront CapEx hardware purchases." },
  { cat: "cloud", topic: "c_cost", q: "Which of the following is an example of a capital expenditure (CapEx)?", options: ["A monthly Azure subscription bill", "Purchasing physical servers and networking hardware for a datacenter", "Paying per second for an Azure VM", "Egress data transfer charges"], answer: 1, explain: "Buying physical assets like servers up front is CapEx; ongoing usage-based cloud charges are OpEx." },
  { cat: "cloud", topic: "c_cost", q: "Which statement best defines the consumption-based model of cloud computing?", options: ["You pay a fixed annual fee regardless of usage", "You pay only for the resources you use, with no upfront cost", "You must purchase hardware before deploying", "You pay only for storage, never compute"], answer: 1, explain: "Consumption-based pricing has no upfront cost — you pay only for what you use and can stop paying when you stop using resources." },
  { cat: "cloud", topic: "c_cost", q: "A finance director notes that moving to Azure converts large, unpredictable hardware refresh purchases into a steadier monthly operating cost. Which benefit does this describe?", options: ["Shifting from OpEx to CapEx", "Shifting from CapEx to OpEx", "Eliminating all costs", "Removing the need for budgeting"], answer: 1, explain: "Cloud adoption typically shifts large upfront CapEx into ongoing, predictable OpEx." },
  { cat: "cloud", topic: "c_cost", q: "A company's workload is busy only a few hours per day. Which cloud cost advantage lets them stop paying for compute the rest of the time?", options: ["Reserved capacity contracts", "Consumption-based billing with the ability to scale down/stop resources", "Capital depreciation", "Fixed licensing"], answer: 1, explain: "With consumption-based billing you can scale down or deallocate resources when they're not needed and stop incurring charges." },

  /* --- Shared Responsibility (c_shared) --- */
  { cat: "cloud", topic: "c_shared", q: "Your company is deploying a web application using Azure Virtual Machines. The security team wants to understand who is responsible for various security aspects under the shared responsibility model. Which security task is Microsoft's responsibility in this scenario?", options: ["Managing the physical security of the datacenter where the virtual machines are hosted", "Ensuring the network security group (NSG) rules are properly configured to restrict traffic to the virtual machines", "Configuring access permissions for users who can manage the virtual machines through Microsoft Entra ID", "Installing and maintaining antimalware software on the guest operating system of the virtual machines"], answer: 0, explain: "Physical datacenter, hosts, and physical network are always the provider's responsibility. With IaaS VMs, the customer handles NSGs, guest OS, identity, and apps." },
  { cat: "cloud", topic: "c_shared", q: "Under the shared responsibility model, which responsibilities are ALWAYS retained by the customer regardless of whether they use IaaS, PaaS, or SaaS?", options: ["Physical hosts and network", "Information/data, devices, and accounts/identities", "Operating system patching", "Datacenter power and cooling"], answer: 1, explain: "Data, devices, and accounts/identities are always the customer's responsibility across all service models." },
  { cat: "cloud", topic: "c_shared", q: "A company uses a PaaS service such as Azure App Service. Who is responsible for patching the underlying operating system?", options: ["The customer", "Microsoft (the cloud provider)", "It is never patched", "A third-party vendor"], answer: 1, explain: "In PaaS, the provider manages the OS and runtime; the customer manages only their application and data." },
  { cat: "cloud", topic: "c_shared", q: "An organization adopts Microsoft 365 (a SaaS product). Which task remains the customer's responsibility?", options: ["Patching the application servers", "Maintaining the physical datacenter", "Managing user accounts, identities, and their data", "Updating the underlying operating system"], answer: 2, explain: "Even in SaaS, the customer is always responsible for their data, devices, and accounts/identities." },
  { cat: "cloud", topic: "c_shared", q: "In an IaaS deployment, which of these is the customer responsible for configuring?", options: ["Physical security of the datacenter", "The host hypervisor", "The guest operating system and its updates", "The physical network cabling"], answer: 2, explain: "With IaaS the customer manages the guest OS (including updates), runtime, applications, and data; the provider manages the physical infrastructure and hypervisor." },

  /* --- Cloud Benefits (c_benefits) --- */
  { cat: "cloud", topic: "c_benefits", q: "A retail company runs an e-commerce web application on Azure. During normal business hours, the application serves approximately 1,000 users. However, during seasonal sales events, traffic increases to 50,000 concurrent users. The company wants to ensure the application can handle these traffic spikes while minimizing costs during normal periods. Which cloud capability best addresses this requirement?", options: ["Geo-distribution", "Vertical scaling (scaling up)", "High availability", "Horizontal scaling (scaling out)"], answer: 3, explain: "Horizontal scaling (scaling out) adds more instances to handle spikes and removes them afterward, matching capacity to demand and minimizing cost during quiet periods." },
  { cat: "cloud", topic: "c_benefits", q: "An application needs more processing power, so the team increases the CPU and RAM of the existing virtual machine rather than adding more machines. What type of scaling is this?", options: ["Horizontal scaling (scaling out)", "Vertical scaling (scaling up)", "Geo-distribution", "Load balancing"], answer: 1, explain: "Adding more power (CPU/RAM) to an existing resource is vertical scaling (scaling up). Adding more instances is horizontal scaling." },
  { cat: "cloud", topic: "c_benefits", q: "Which cloud benefit describes a system's ability to remain operational and accessible with minimal downtime, often backed by a service-level agreement?", options: ["Elasticity", "High availability", "Agility", "Scalability"], answer: 1, explain: "High availability keeps services running with minimal downtime, frequently expressed as an SLA percentage such as 99.9%." },
  { cat: "cloud", topic: "c_benefits", q: "A system is designed so that it can automatically recover and continue functioning even when components fail. Which cloud benefit does this describe?", options: ["Reliability", "CapEx", "Multi-tenancy", "Latency"], answer: 0, explain: "Reliability is the ability of a system to recover from failures and keep working, supported by a globally distributed design." },
  { cat: "cloud", topic: "c_benefits", q: "A company's workload demand is highly unpredictable. They want Azure to automatically add resources when demand rises and remove them when it falls, so they only pay for what they need at any moment. Which characteristic is this?", options: ["Disaster recovery", "Elasticity", "Geo-distribution", "Fault tolerance"], answer: 1, explain: "Elasticity is the automatic addition/removal of resources to match changing demand in near real time." },
  { cat: "cloud", topic: "c_benefits", q: "A global company wants to deploy copies of its application in datacenters close to users in different continents to reduce latency. Which cloud benefit does this leverage?", options: ["Vertical scaling", "Global reach / geo-distribution", "CapEx", "Single-region deployment"], answer: 1, explain: "Global reach (geo-distribution) lets you deploy resources in regions worldwide to serve users with low latency." },
  { cat: "cloud", topic: "c_benefits", q: "Which benefit allows an organization to deploy and test new ideas quickly without procuring physical hardware?", options: ["Agility", "Depreciation", "Co-location", "Capital expenditure"], answer: 0, explain: "Agility is the ability to rapidly provision and deprovision resources, accelerating development and time to market." },
  { cat: "cloud", topic: "c_benefits", q: "A company wants to ensure it can restore operations in another location if its primary region suffers a major outage. Which capability addresses this?", options: ["Vertical scaling", "Disaster recovery", "Multi-tenancy", "Consumption pricing"], answer: 1, explain: "Disaster recovery provides the ability to recover services and data in an alternate location after a major failure." },

  /* --- Service Types IaaS/PaaS/SaaS (c_types) --- */
  { cat: "cloud", topic: "c_types", q: "A startup wants to deploy a web application without managing any servers, operating system patching, or runtime updates. They want to focus only on their application code and data. Which cloud service model best fits this requirement?", options: ["IaaS (Infrastructure as a Service)", "PaaS (Platform as a Service)", "On-premises", "Co-location"], answer: 1, explain: "PaaS (e.g., Azure App Service) manages the OS, runtime, and infrastructure so developers focus only on the app and data." },
  { cat: "cloud", topic: "c_types", q: "Microsoft 365 and Outlook are examples of which cloud service model?", options: ["IaaS", "PaaS", "SaaS", "DaaS"], answer: 2, explain: "These are ready-to-use, fully managed software products — Software as a Service (SaaS)." },
  { cat: "cloud", topic: "c_types", q: "Which cloud service model gives the customer the MOST control over the operating system and installed software?", options: ["SaaS", "PaaS", "IaaS", "FaaS"], answer: 2, explain: "IaaS gives the most control: the customer manages the OS, runtime, and applications while the provider manages physical infrastructure." },
  { cat: "cloud", topic: "c_types", q: "A company wants to migrate existing applications to the cloud with minimal changes ('lift and shift'), keeping full control of the operating system. Which service model is most appropriate?", options: ["SaaS", "PaaS", "IaaS", "Serverless"], answer: 2, explain: "IaaS (Azure Virtual Machines) is ideal for lift-and-shift migrations where you need full OS control." },
  { cat: "cloud", topic: "c_types", q: "A development team needs a fully managed relational database and does not want to manage the underlying servers or operating system. Which service model does Azure SQL Database represent?", options: ["IaaS", "PaaS", "SaaS", "On-premises"], answer: 1, explain: "Azure SQL Database is a PaaS offering — Microsoft manages the infrastructure and OS while you manage the database and data." },
  { cat: "cloud", topic: "c_types", q: "Which cloud service model places the LEAST management responsibility on the customer?", options: ["IaaS", "PaaS", "SaaS", "All require equal responsibility"], answer: 2, explain: "SaaS places the least responsibility on the customer — they only manage data, devices, and accounts." },
  { cat: "cloud", topic: "c_types", q: "A company needs full administrative access to install custom drivers and specialized software on a server in the cloud. Which model supports this?", options: ["SaaS", "PaaS", "IaaS", "FaaS"], answer: 2, explain: "IaaS provides a virtual machine where you have full administrative control of the OS to install custom software and drivers." },
  { cat: "cloud", topic: "c_types", q: "Azure Functions lets developers run code without provisioning or managing servers. Which cloud category does this serverless model fall under?", options: ["IaaS", "PaaS", "SaaS", "On-premises"], answer: 1, explain: "Serverless services like Azure Functions are a form of PaaS — the platform manages all infrastructure and you provide only code." },

  /* ===================== ARCHITECTURE & SERVICES ===================== */

  /* --- Core Architecture (a_core) --- */
  { cat: "arch", topic: "a_core", q: "A company is planning to migrate their on-premises infrastructure to Azure. They need to assess their current environment, which includes 50 physical servers running various workloads, multiple databases, and web applications. The IT manager wants to discover dependencies between servers, get Azure cost estimates, and receive right-sizing recommendations before migrating. Which Azure service should they use to accomplish these assessment tasks?", options: ["Azure Monitor", "Microsoft Defender for Cloud", "Azure Advisor", "Azure Migrate"], answer: 3, explain: "Azure Migrate is the central hub for discovering, assessing (dependencies, right-sizing, cost estimates), and migrating on-premises servers, databases, and apps." },
  { cat: "arch", topic: "a_core", q: "Your company is deploying a mission-critical application in Azure that must maintain availability even if an entire Azure datacenter becomes unavailable due to a natural disaster. The application stores customer data that must be automatically replicated to a geographically distant location to ensure business continuity. Which Azure feature should you rely on to achieve this geographic redundancy?", options: ["Resource Groups", "Availability Zones", "Region Pairs", "Availability Sets"], answer: 2, explain: "Region pairs are two regions (300+ miles apart) in the same geography used for disaster recovery and geographic redundancy across regions. Availability Zones only protect within a single region." },
  { cat: "arch", topic: "a_core", q: "An application must keep running even if a single datacenter within a region fails. Which feature provides this protection within one region?", options: ["Region pairs", "Availability Zones", "Resource groups", "Management groups"], answer: 1, explain: "Availability Zones are physically separate datacenters within a region (independent power, cooling, networking), protecting against datacenter-level failure." },
  { cat: "arch", topic: "a_core", q: "A region pair consists of two regions in the same geography that are at least how far apart?", options: ["50 miles (80 km)", "100 miles (160 km)", "300 miles (480 km)", "1,000 miles (1,600 km)"], answer: 2, explain: "Azure region pairs are at least 300 miles apart to reduce the chance that a single disaster affects both regions." },
  { cat: "arch", topic: "a_core", q: "Which statement best describes an Azure resource group?", options: ["A billing boundary for an entire organization", "A logical container that holds related Azure resources", "A physically separate datacenter", "A worldwide network of regions"], answer: 1, explain: "A resource group is a logical container for related resources; a resource belongs to exactly one group, and deleting the group deletes its contents." },
  { cat: "arch", topic: "a_core", q: "What is the correct Azure management hierarchy, from the top level down?", options: ["Subscriptions → Management groups → Resource groups → Resources", "Management groups → Subscriptions → Resource groups → Resources", "Resource groups → Subscriptions → Management groups → Resources", "Resources → Resource groups → Subscriptions → Management groups"], answer: 1, explain: "Top to bottom: Management groups → Subscriptions → Resource groups → Resources." },
  { cat: "arch", topic: "a_core", q: "An enterprise has 20 Azure subscriptions and wants to apply the same governance policies and access controls across all of them at once. Which scope should they use?", options: ["Resource groups", "Management groups", "A single subscription", "Individual resources"], answer: 1, explain: "Management groups sit above subscriptions and let you apply policy and RBAC across many subscriptions simultaneously." },
  { cat: "arch", topic: "a_core", q: "Which Azure component acts as the deployment and management layer through which all requests (portal, CLI, PowerShell, SDK) are authenticated and authorized?", options: ["Azure Monitor", "Azure Resource Manager (ARM)", "Azure Policy", "Azure Advisor"], answer: 1, explain: "Azure Resource Manager (ARM) is the consistent management layer that handles all create/update/delete requests and enables templates, RBAC, tags, and locks." },
  { cat: "arch", topic: "a_core", q: "An Azure subscription primarily serves as which kind of boundary?", options: ["A physical networking boundary", "A billing and access-management boundary", "A datacenter boundary", "A DNS boundary"], answer: 1, explain: "A subscription is a logical unit used as a boundary for billing, access management, and certain service limits/quotas." },
  { cat: "arch", topic: "a_core", q: "A company wants to protect VMs in a single datacenter against rack/hardware failures and host maintenance events by distributing them across fault domains and update domains. What should they use?", options: ["Availability Zones", "Availability Sets", "Region pairs", "Resource groups"], answer: 1, explain: "Availability Sets distribute VMs across fault domains and update domains within a datacenter to protect against hardware failures and planned maintenance." },

  /* --- Compute (a_compute) --- */
  { cat: "arch", topic: "a_compute", q: "A company is developing a mobile application that needs to process image uploads from users. The image processing workload is unpredictable, with usage spikes occurring randomly throughout the day. The company wants to minimize costs by only paying for compute resources when images are actually being processed. Which Azure compute solution best meets these requirements?", options: ["Azure Functions with a consumption plan", "Azure App Service with an Always On feature", "Azure Container Instances running continuously", "Azure Virtual Machines with auto-scaling enabled"], answer: 0, explain: "Azure Functions on a consumption plan is serverless and event-driven — you pay only per execution, ideal for spiky, intermittent processing." },
  { cat: "arch", topic: "a_compute", q: "A company needs to run and orchestrate hundreds of containers across a cluster, with automated scaling, self-healing, and rolling updates. Which Azure service should they use?", options: ["Azure Container Instances", "Azure Kubernetes Service (AKS)", "Azure App Service", "Azure Functions"], answer: 1, explain: "AKS is the managed Kubernetes service for orchestrating large numbers of containers with scaling and self-healing." },
  { cat: "arch", topic: "a_compute", q: "Your organization needs to deploy identical development environments and have them automatically scale out and in based on CPU load, all behind a load balancer. Which compute option is most appropriate?", options: ["A single Azure Virtual Machine", "Virtual Machine Scale Sets", "Azure Container Instances", "Azure Functions"], answer: 1, explain: "Virtual Machine Scale Sets create and manage a group of identical, load-balanced VMs that automatically scale based on demand or schedule." },
  { cat: "arch", topic: "a_compute", q: "A developer wants the fastest, simplest way to run a single container in Azure for a short task without managing any orchestration or servers. Which service fits best?", options: ["Azure Kubernetes Service", "Azure Container Instances (ACI)", "Azure Virtual Machines", "Azure App Service"], answer: 1, explain: "Azure Container Instances (ACI) is the quickest way to run an isolated, single container without orchestration overhead." },
  { cat: "arch", topic: "a_compute", q: "A team wants a fully managed platform to host a public-facing web app and REST API, with built-in scaling and deployment slots, without managing the underlying servers. Which service should they use?", options: ["Azure Virtual Machines", "Azure App Service", "Azure Container Instances", "Azure Batch"], answer: 1, explain: "Azure App Service is a PaaS for hosting web apps and APIs with built-in scaling, deployment slots, and no server management." },
  { cat: "arch", topic: "a_compute", q: "A company wants to provide its 500 remote employees with secure, cloud-hosted Windows desktops accessible from any device. Which Azure service should they use?", options: ["Azure Virtual Machines", "Azure Virtual Desktop", "Azure App Service", "Azure Functions"], answer: 1, explain: "Azure Virtual Desktop delivers virtualized Windows desktops and apps from the cloud, accessible from anywhere (including multi-session Windows)." },
  { cat: "arch", topic: "a_compute", q: "Which statement correctly contrasts containers with virtual machines?", options: ["Containers each include a full guest operating system, making them heavier than VMs", "Containers virtualize the OS, are lightweight, and share the host kernel, starting faster than VMs", "VMs are always smaller and faster to start than containers", "Containers cannot be used in Azure"], answer: 1, explain: "Containers virtualize the OS and share the host kernel, making them lightweight and fast to start; VMs virtualize hardware and each run a full OS." },
  { cat: "arch", topic: "a_compute", q: "A workload requires running a piece of code only when a message arrives on a queue, and the team does not want to pay for idle compute. Which compute service is the best match?", options: ["Azure Virtual Machines", "Azure Functions", "Azure Kubernetes Service", "Availability Sets"], answer: 1, explain: "Azure Functions is event-driven serverless compute — it runs code in response to triggers (like a queue message) and you pay only when it runs." },

  /* --- Networking (a_network) --- */
  { cat: "arch", topic: "a_network", q: "A financial services company needs to establish a connection between their on-premises datacenter and Azure. The company requires a private, dedicated connection that does not traverse the public internet due to regulatory compliance requirements. The connection must provide predictable network performance and support bandwidth options up to 100 Gbps. Which Azure networking service should the company implement?", options: ["Azure ExpressRoute", "Azure Virtual WAN", "Azure Bastion", "Azure VPN Gateway"], answer: 0, explain: "Azure ExpressRoute provides a private, dedicated connection that bypasses the public internet, with predictable performance and high bandwidth — ideal for compliance-sensitive workloads." },
  { cat: "arch", topic: "a_network", q: "A company has two branch offices that need to connect to their Azure virtual network securely over the public internet using encrypted tunnels, without the cost of a dedicated circuit. Which service should they use?", options: ["Azure ExpressRoute", "Azure VPN Gateway", "Azure DNS", "VNet peering"], answer: 1, explain: "A VPN Gateway creates encrypted tunnels over the public internet (site-to-site), connecting on-premises networks to Azure at lower cost than ExpressRoute." },
  { cat: "arch", topic: "a_network", q: "Your company has two Azure virtual networks, VNet-Prod and VNet-Dev, and wants resources in them to communicate privately over the Microsoft backbone as if on the same network. Which feature enables this?", options: ["VPN Gateway", "VNet peering", "ExpressRoute", "Azure DNS"], answer: 1, explain: "VNet peering connects two virtual networks so their resources communicate privately and efficiently over the Microsoft backbone network." },
  { cat: "arch", topic: "a_network", q: "What is the primary purpose of an Azure Virtual Network (VNet)?", options: ["To store unstructured data", "To provide an isolated private network in Azure for secure resource communication", "To monitor application performance", "To manage user identities"], answer: 1, explain: "A VNet is a logically isolated private network enabling Azure resources to communicate securely with each other, the internet, and on-premises networks." },
  { cat: "arch", topic: "a_network", q: "A company needs to host and resolve their DNS domains using Azure infrastructure for fast, reliable name resolution. Which service should they use?", options: ["Azure DNS", "Azure Firewall", "Azure Load Balancer", "Azure Bastion"], answer: 0, explain: "Azure DNS hosts DNS domains and provides name resolution using Microsoft's global infrastructure." },
  { cat: "arch", topic: "a_network", q: "Which key difference distinguishes ExpressRoute from a VPN Gateway connection?", options: ["ExpressRoute traffic travels over the public internet; VPN does not", "ExpressRoute provides a private connection that bypasses the public internet, while VPN encrypts traffic over the public internet", "VPN is always faster and more reliable than ExpressRoute", "They are identical services"], answer: 1, explain: "ExpressRoute is a private dedicated link that avoids the public internet; a VPN Gateway encrypts traffic that still travels over the public internet." },
  { cat: "arch", topic: "a_network", q: "Which Azure networking component is used to filter inbound and outbound network traffic to resources within a virtual network by allowing or denying traffic based on rules?", options: ["Network Security Group (NSG)", "Azure DNS", "VNet peering", "ExpressRoute"], answer: 0, explain: "A Network Security Group (NSG) contains rules that allow or deny inbound/outbound traffic to resources in a VNet." },

  /* --- Storage (a_storage) --- */
  { cat: "arch", topic: "a_storage", q: "A company needs to store large amounts of unstructured data including images, videos, and log files for their web application. The data will be accessed frequently during the first month after upload, but afterward will rarely be accessed. The company wants to minimize storage costs while ensuring the data remains available if needed. Which Azure storage solution should they implement?", options: ["Azure Queue Storage with automatic archiving enabled", "Azure Table Storage with partitioning by upload date", "Azure Files with Premium performance tier for the first month, then switch to Standard tier", "Azure Blob Storage with a lifecycle management policy to move data to the Cool access tier after 30 days"], answer: 3, explain: "Blob storage is for unstructured data; a lifecycle management policy can automatically move blobs from Hot to Cool after 30 days to cut costs while keeping data accessible." },
  { cat: "arch", topic: "a_storage", q: "A company stores critical financial data in Azure Storage accounts. The company requires protection against datacenter-level failures within a region but does not need protection against region-wide outages. The solution must minimize costs while meeting the redundancy requirement. Which Azure Storage redundancy option should the company select?", options: ["Locally redundant storage (LRS)", "Geo-zone-redundant storage (GZRS)", "Geo-redundant storage (GRS)", "Zone-redundant storage (ZRS)"], answer: 3, explain: "ZRS replicates data synchronously across three availability zones in the primary region, protecting against datacenter (zone) failure without the cost of geo-replication." },
  { cat: "arch", topic: "a_storage", q: "A company needs storage that protects data against a complete regional outage by replicating it to a secondary region hundreds of miles away. Which redundancy option meets this requirement?", options: ["Locally redundant storage (LRS)", "Zone-redundant storage (ZRS)", "Geo-redundant storage (GRS)", "Premium storage"], answer: 2, explain: "GRS replicates data to a paired secondary region, protecting against a full regional outage." },
  { cat: "arch", topic: "a_storage", q: "Which Azure Storage redundancy option is the lowest cost and replicates data three times within a single datacenter?", options: ["GRS", "GZRS", "ZRS", "LRS"], answer: 3, explain: "LRS copies data three times within one datacenter — the cheapest option, protecting only against drive/server failure." },
  { cat: "arch", topic: "a_storage", q: "A company needs to store rarely accessed backup data for several years at the absolute lowest storage cost and can tolerate hours of retrieval latency. Which blob access tier is most appropriate?", options: ["Hot", "Cool", "Cold", "Archive"], answer: 3, explain: "The Archive tier offers the lowest storage cost for rarely accessed, long-term data; retrieval requires rehydration and takes time." },
  { cat: "arch", topic: "a_storage", q: "A company needs to transfer 80 TB of data to Azure but has limited network bandwidth that would make an online transfer take months. What is the best option?", options: ["AzCopy over the internet", "Azure File Sync", "Azure Data Box", "Azure Migrate"], answer: 2, explain: "Azure Data Box is a physical appliance shipped to you for offline bulk data transfer when network transfer is impractical." },
  { cat: "arch", topic: "a_storage", q: "A team needs fully managed file shares in the cloud that can be mounted concurrently by cloud and on-premises machines using the SMB protocol. Which service should they use?", options: ["Azure Blob Storage", "Azure Files", "Azure Queue Storage", "Azure Table Storage"], answer: 1, explain: "Azure Files provides fully managed SMB/NFS file shares that can be mounted from cloud and on-premises systems." },
  { cat: "arch", topic: "a_storage", q: "Which Azure Storage service is designed to store large amounts of unstructured object data such as images and video?", options: ["Azure Table Storage", "Azure Queue Storage", "Azure Blob Storage", "Azure Disk Storage"], answer: 2, explain: "Azure Blob Storage is object storage optimized for massive amounts of unstructured data." },
  { cat: "arch", topic: "a_storage", q: "A company needs maximum durability for data that must survive both a zone failure AND a complete regional outage. Which redundancy option should they choose?", options: ["LRS", "ZRS", "GRS", "GZRS"], answer: 3, explain: "GZRS (geo-zone-redundant storage) combines zone redundancy in the primary region with geo-replication to a secondary region — the highest durability." },

  /* --- Identity & Security (a_identity) --- */
  { cat: "arch", topic: "a_identity", q: "Your organization has 500 employees who need to access both Microsoft 365 applications and Azure resources. The IT department wants to implement a centralized identity solution where users can sign in once and access all required resources without additional authentication prompts. Which Azure service should you recommend?", options: ["Azure Key Vault", "Azure Active Directory Domain Services (Azure AD DS)", "Azure Virtual Network", "Microsoft Entra ID"], answer: 3, explain: "Microsoft Entra ID (formerly Azure AD) is the cloud identity and access service that provides centralized authentication and single sign-on across Microsoft 365 and Azure resources." },
  { cat: "arch", topic: "a_identity", q: "A retail company is developing a mobile shopping application that will allow customers to create accounts using their email addresses or social media credentials like Facebook and Google. The application needs to provide secure authentication and profile management for millions of consumer users. Which Azure service should the company implement?", options: ["Microsoft Entra Domain Services", "Microsoft Entra ID B2C (Business-to-Consumer)", "Microsoft Entra ID B2B (Business-to-Business)", "Azure Active Directory Connect"], answer: 1, explain: "Microsoft Entra ID B2C is built for customer/consumer identity at scale, supporting sign-up/sign-in with email or social identity providers." },
  { cat: "arch", topic: "a_identity", q: "What is the difference between authentication and authorization?", options: ["They are the same thing", "Authentication proves who you are; authorization determines what you are allowed to do", "Authorization proves who you are; authentication determines what you can do", "Both apply only to on-premises systems"], answer: 1, explain: "Authentication (AuthN) verifies identity; authorization (AuthZ) determines access rights. Authentication happens first." },
  { cat: "arch", topic: "a_identity", q: "A company wants to require users to verify their identity with both a password and a code from their phone when signing in. Which security capability provides this?", options: ["Single sign-on (SSO)", "Multi-factor authentication (MFA)", "Conditional Access", "Resource locks"], answer: 1, explain: "MFA requires two or more verification factors (e.g., something you know + something you have), greatly improving sign-in security." },
  { cat: "arch", topic: "a_identity", q: "Your organization wants to require multi-factor authentication only when users sign in from outside the corporate network or from an unfamiliar location. Which Microsoft Entra feature enforces access decisions based on such signals?", options: ["Azure Policy", "Conditional Access", "Role-based access control (RBAC)", "Resource locks"], answer: 1, explain: "Conditional Access evaluates signals (user, location, device, risk) and can allow, block, or require MFA accordingly." },
  { cat: "arch", topic: "a_identity", q: "A company wants partner organizations to collaborate on shared resources using their own existing corporate credentials. Which Microsoft Entra capability supports this?", options: ["Entra ID B2C", "Entra External ID / B2B collaboration", "Conditional Access", "Azure Bastion"], answer: 1, explain: "Microsoft Entra B2B collaboration lets external partners/guests access your resources using their own identities." },
  { cat: "arch", topic: "a_identity", q: "Which on-premises identity technology uses Kerberos and LDAP and is used to manage domain-joined Windows devices and Group Policy?", options: ["Microsoft Entra ID", "Active Directory Domain Services (AD DS)", "Microsoft Entra ID B2C", "Conditional Access"], answer: 1, explain: "AD DS is the traditional on-premises directory using Kerberos/LDAP; Microsoft Entra ID is the cloud-based identity service using modern protocols." },
  { cat: "arch", topic: "a_identity", q: "A user signs in once in the morning and can then access email, the HR portal, and several other apps without re-entering credentials. Which capability enables this?", options: ["Multi-factor authentication", "Single sign-on (SSO)", "Resource locks", "Tagging"], answer: 1, explain: "Single sign-on (SSO) lets a user authenticate once and access multiple applications without repeated sign-ins." },

  /* ===================== MANAGEMENT & GOVERNANCE ===================== */

  /* --- Cost Management (g_cost) --- */
  { cat: "govern", topic: "g_cost", q: "Your organization has deployed multiple Azure resources across different departments including virtual machines, storage accounts, and Azure SQL databases. The finance department needs to generate monthly cost reports showing expenses for each department separately. What is the most effective way to use tags to accomplish this requirement?", options: ["Apply a Department tag only to resource groups, as tags automatically inherit from resource groups to all contained resources for billing purposes", "Apply Department tags to resources and enable tag enforcement policies, which will automatically generate cost reports grouped by department", "Apply a Department tag with values like \"Finance\", \"Marketing\", and \"IT\" to each resource, then use cost analysis to filter and group expenses by the Department tag", "Create separate Azure subscriptions for each department and apply Department tags at the subscription level to track costs"], answer: 2, explain: "Tags are name/value pairs applied to resources; applying a Department tag to each resource and then filtering/grouping in Cost analysis produces per-department cost reports. (Note: resource tags do NOT automatically inherit from resource groups for billing.)" },
  { cat: "govern", topic: "g_cost", q: "Before deploying any resources, an architect wants to estimate the monthly cost of a proposed solution made up of VMs, storage, and a database. Which tool should they use?", options: ["Microsoft Cost Management", "Total Cost of Ownership (TCO) Calculator", "Azure Pricing Calculator", "Azure Advisor"], answer: 2, explain: "The Azure Pricing Calculator estimates the cost of services before you deploy them." },
  { cat: "govern", topic: "g_cost", q: "A company wants to build a business case comparing the cost of keeping workloads in their on-premises datacenter versus moving them to Azure. Which tool is designed for this comparison?", options: ["Pricing Calculator", "Total Cost of Ownership (TCO) Calculator", "Cost Management", "Azure Monitor"], answer: 1, explain: "The TCO Calculator estimates the savings of moving on-premises workloads to Azure by comparing the two." },
  { cat: "govern", topic: "g_cost", q: "After deploying resources, a team wants to monitor actual spending, set budgets, and receive alerts when costs approach a threshold. Which tool should they use?", options: ["Pricing Calculator", "TCO Calculator", "Microsoft Cost Management", "Azure Policy"], answer: 2, explain: "Microsoft Cost Management lets you analyze actual spend, create budgets, and configure alerts." },
  { cat: "govern", topic: "g_cost", q: "Which of the following does NOT directly affect the cost of an Azure resource?", options: ["The region where it is deployed", "Outbound (egress) data transfer", "The color theme chosen in the Azure portal", "The resource type and size"], answer: 2, explain: "The portal's color theme has no cost impact. Region, egress data transfer, resource type/size, and subscription type all affect cost." },
  { cat: "govern", topic: "g_cost", q: "Regarding Azure data transfer costs, which statement is generally true?", options: ["Both inbound and outbound data transfer are always free", "Inbound (ingress) data is typically free, while outbound (egress) data is charged", "Outbound data is free, inbound is charged", "Data transfer is never billed"], answer: 1, explain: "Inbound (ingress) data transfer to Azure is generally free, while outbound (egress) data transfer is typically billed." },
  { cat: "govern", topic: "g_cost", q: "A finance team wants to be notified automatically when a subscription's monthly spend exceeds £5,000. Which capability should they configure?", options: ["A budget with alerts in Microsoft Cost Management", "An Azure Policy", "A resource lock", "An NSG rule"], answer: 0, explain: "Budgets in Microsoft Cost Management can trigger alerts when actual or forecast spend crosses a defined threshold." },

  /* --- Governance & Compliance (g_gov) --- */
  { cat: "govern", topic: "g_gov", q: "Your organization has multiple Azure subscriptions across different departments. Management requires a solution to enforce that all virtual machines must have specific tags applied (Department, CostCenter, and Owner) before they can be created. Which Azure governance feature should you implement to meet this requirement?", options: ["Management groups", "Azure Policy", "Resource locks", "Role-based access control (RBAC)"], answer: 1, explain: "Azure Policy enforces organizational rules — such as requiring specific tags — and can deny creation of resources that don't comply." },
  { cat: "govern", topic: "g_gov", q: "You need to grant a contractor permission to manage virtual machines in a single resource group, but nothing else in the subscription. Which feature should you use, following least privilege?", options: ["Azure Policy", "Role-based access control (RBAC)", "Resource locks", "Tags"], answer: 1, explain: "RBAC assigns roles scoped to a specific resource, resource group, subscription, or management group, granting only the needed permissions." },
  { cat: "govern", topic: "g_gov", q: "An administrator wants to prevent a critical production resource from being accidentally deleted, while still allowing it to be read and modified. Which feature should they apply?", options: ["A ReadOnly resource lock", "A CanNotDelete resource lock", "An Azure Policy", "A tag"], answer: 1, explain: "A CanNotDelete lock allows reading and modifying the resource but blocks deletion." },
  { cat: "govern", topic: "g_gov", q: "An auditor needs Microsoft's official compliance certifications, audit reports, and security/privacy documentation for Azure. Where should they look?", options: ["Azure Advisor", "Service Trust Portal", "Microsoft Cost Management", "Azure Monitor"], answer: 1, explain: "The Service Trust Portal publishes Microsoft's compliance reports, certifications, and security/privacy resources." },
  { cat: "govern", topic: "g_gov", q: "A company must ensure resources can only be deployed to the UK South and UK West regions to meet data-residency rules. Which feature enforces this restriction?", options: ["Resource locks", "Azure Policy (allowed locations)", "Tags", "RBAC"], answer: 1, explain: "Azure Policy can restrict the allowed locations/regions for resource deployment, enforcing data-residency requirements." },
  { cat: "govern", topic: "g_gov", q: "An organization needs to discover, classify, and govern data across on-premises, multi-cloud, and SaaS sources from one place. Which solution should they use?", options: ["Microsoft Purview", "Azure Advisor", "Azure Monitor", "Resource locks"], answer: 0, explain: "Microsoft Purview is a unified data governance and compliance solution spanning on-premises, multi-cloud, and SaaS data." },
  { cat: "govern", topic: "g_gov", q: "What does an Azure Service Level Agreement (SLA) represent?", options: ["A discount for buying reserved instances", "Microsoft's formal commitment to the uptime/performance of a service", "A list of regions where a service is available", "A backup retention schedule"], answer: 1, explain: "An SLA is Microsoft's formal commitment to a service's uptime/performance. Free and preview tiers usually have no SLA." },
  { cat: "govern", topic: "g_gov", q: "An administrator wants to ensure a resource cannot be changed OR deleted by anyone, even users with owner permissions. Which lock type should they apply?", options: ["CanNotDelete lock", "ReadOnly lock", "RBAC role", "Tag"], answer: 1, explain: "A ReadOnly lock allows only reading the resource — no modification or deletion — overriding even owner permissions." },
  { cat: "govern", topic: "g_gov", q: "Which statement best distinguishes Azure Policy from RBAC?", options: ["They are identical", "RBAC controls what actions a user can perform (access); Azure Policy controls what resources can exist and how they're configured (compliance)", "Azure Policy controls user access; RBAC enforces resource compliance", "Both only apply to storage accounts"], answer: 1, explain: "RBAC governs who can do what (access), while Azure Policy governs the properties/compliance of resources themselves." },

  /* --- Management Tools (g_tools) --- */
  { cat: "govern", topic: "g_tools", q: "Your organization needs to deploy 15 identical virtual machines across three different Azure regions for a new application. The IT manager wants to ensure consistency in the configuration of all virtual machines and simplify the deployment process. Which Azure Resource Manager capability would be most appropriate for this scenario?", options: ["Use Azure Resource Manager locks to prevent changes to the virtual machines after deployment", "Use Azure Resource Manager resource groups to organize the virtual machines by region", "Use Azure Resource Manager role-based access control (RBAC) to manage permissions for the virtual machines", "Use Azure Resource Manager templates to define the infrastructure and deploy it consistently across all regions"], answer: 3, explain: "ARM templates define infrastructure as code, enabling repeatable, consistent, automated deployments of identical resources across regions." },
  { cat: "govern", topic: "g_tools", q: "Your company currently deploys Azure resources manually through the Azure portal. The IT manager wants to improve deployment consistency, reduce human error, and enable the team to version-control infrastructure configurations. Which approach best addresses these requirements?", options: ["Use Azure Resource Manager (ARM) templates or Bicep files to define infrastructure in code, which can be stored in a version control system and deployed repeatedly", "Assign multiple administrators to review each other's work when manually creating resources through the Azure portal", "Create detailed documentation with screenshots showing each step to create resources in the Azure portal, and store the documentation in a SharePoint library", "Create a video tutorial demonstrating how to provision resources through the Azure portal and require all team members to watch it before deployment"], answer: 0, explain: "Infrastructure as Code with ARM templates or Bicep is declarative, repeatable, version-controllable, and reduces human error — exactly what's needed." },
  { cat: "govern", topic: "g_tools", q: "An administrator wants to manage Azure from a browser using either Bash or PowerShell without installing anything locally. Which tool should they use?", options: ["Azure CLI installed on a laptop", "Azure Cloud Shell", "Azure PowerShell module installed locally", "ARM templates"], answer: 1, explain: "Azure Cloud Shell is a browser-based shell offering Bash or PowerShell with no local installation required." },
  { cat: "govern", topic: "g_tools", q: "A team prefers a domain-specific language with cleaner, simpler syntax than JSON for authoring infrastructure as code, which then compiles down to ARM templates. Which should they use?", options: ["YAML", "Bicep", "Terraform HCL", "XML"], answer: 1, explain: "Bicep is Microsoft's DSL for Azure IaC with simpler syntax that transpiles to ARM JSON." },
  { cat: "govern", topic: "g_tools", q: "Which tool provides a unified, web-based graphical interface to build, manage, and monitor Azure resources?", options: ["Azure Cloud Shell", "The Azure portal", "Azure CLI", "Bicep"], answer: 1, explain: "The Azure portal is the web-based GUI for creating, managing, and monitoring Azure resources." },
  { cat: "govern", topic: "g_tools", q: "An administrator wants to script Azure management tasks using Verb-Noun style cmdlets. Which tool are they using?", options: ["Azure CLI", "Azure PowerShell", "Bicep", "The Azure portal"], answer: 1, explain: "Azure PowerShell uses cmdlets in a Verb-Noun format (e.g., New-AzVM) for scripting Azure management." },
  { cat: "govern", topic: "g_tools", q: "A cross-platform administrator wants to manage Azure using simple commands that begin with 'az' on Windows, macOS, or Linux. Which tool should they use?", options: ["Azure PowerShell", "Azure CLI", "ARM templates", "Bicep"], answer: 1, explain: "The Azure CLI is a cross-platform command-line tool using 'az' commands to manage Azure resources." },

  /* --- Monitoring (g_monitor) --- */
  { cat: "govern", topic: "g_monitor", q: "An IT team wants free, personalized recommendations to improve their Azure environment across cost, security, reliability, operational excellence, and performance. Which service provides this?", options: ["Azure Monitor", "Azure Advisor", "Azure Service Health", "Azure Policy"], answer: 1, explain: "Azure Advisor analyzes your configuration and usage and gives best-practice recommendations across five categories, at no cost." },
  { cat: "govern", topic: "g_monitor", q: "An administrator needs to know whether an Azure region they rely on is currently experiencing an outage or planned maintenance. Which service gives this personalized view?", options: ["Azure Advisor", "Azure Service Health", "Microsoft Cost Management", "Log Analytics"], answer: 1, explain: "Azure Service Health provides a personalized view of the health of the Azure services and regions you use, including outages and planned maintenance." },
  { cat: "govern", topic: "g_monitor", q: "A team wants to write and run KQL (Kusto Query Language) queries against collected log data to investigate an issue. Which tool within Azure Monitor should they use?", options: ["Application Insights", "Log Analytics", "Azure Advisor", "Service Health"], answer: 1, explain: "Log Analytics is the Azure Monitor tool used to edit and run KQL queries against collected logs." },
  { cat: "govern", topic: "g_monitor", q: "A developer wants to monitor a live web application's performance, availability, request rates, and failures, and detect issues proactively. Which tool should they use?", options: ["Application Insights", "Azure Policy", "Microsoft Cost Management", "Resource locks"], answer: 0, explain: "Application Insights (an Azure Monitor feature) monitors live application performance, availability, and usage for developers." },
  { cat: "govern", topic: "g_monitor", q: "Which service is the overarching platform for collecting, analyzing, and acting on telemetry (metrics and logs) from both Azure and on-premises environments?", options: ["Azure Advisor", "Azure Monitor", "Azure Service Health", "Azure Arc"], answer: 1, explain: "Azure Monitor is the comprehensive platform for collecting and acting on metrics and logs across Azure and on-premises." },
  { cat: "govern", topic: "g_monitor", q: "A team wants to be automatically notified (or trigger an automated action) when CPU usage on a VM exceeds 90% for five minutes. Which Azure Monitor feature should they configure?", options: ["Tags", "Alerts", "Resource locks", "Region pairs"], answer: 1, explain: "Azure Monitor alerts notify you or trigger actions when monitoring data crosses a defined threshold or condition." },
  { cat: "govern", topic: "g_monitor", q: "Which statement correctly distinguishes Azure Advisor, Azure Service Health, and Azure Monitor?", options: ["They are three names for the same tool", "Advisor gives improvement recommendations, Service Health reports the status of Azure itself, and Monitor collects telemetry from your resources", "Monitor gives recommendations, Advisor reports outages, Service Health collects logs", "All three only report billing information"], answer: 1, explain: "Advisor = recommendations to improve; Service Health = health/outages of Azure services you use; Monitor = telemetry (metrics/logs) from your own resources." },

];
