/* =====================================================================
   AZ-900 Study Hub — alternate exam question formats
   Adds the question styles the real AZ-900 uses beyond single-answer:
     • "multi"    — multiple-response ("choose two/three"); answers is an array
     • "yesno"    — case-study style statement answered Yes/No
     • "sentence" — "complete the sentence" with one or more dropdowns

   Loaded AFTER js/questions.js and BEFORE js/data.js, appending to the
   shared AZ_QUESTIONS pool so the mock tests pick them up automatically.
   ===================================================================== */
(function () {
  const extra = [

    /* ---------- MULTIPLE RESPONSE (choose two/three) ---------- */
    { type: "multi", cat: "cloud", topic: "c_types", q: "Which TWO of the following are examples of Platform as a Service (PaaS)? (Choose two.)", options: ["Azure Virtual Machines", "Azure App Service", "Azure SQL Database", "Microsoft 365"], answers: [1, 2], explain: "Azure App Service and Azure SQL Database are PaaS — Microsoft manages the OS/runtime. Azure VMs are IaaS; Microsoft 365 is SaaS." },
    { type: "multi", cat: "arch", topic: "a_storage", q: "Which TWO Azure Storage redundancy options protect data against a complete regional outage? (Choose two.)", options: ["Locally redundant storage (LRS)", "Zone-redundant storage (ZRS)", "Geo-redundant storage (GRS)", "Geo-zone-redundant storage (GZRS)"], answers: [2, 3], explain: "GRS and GZRS both replicate to a secondary region, protecting against a regional outage. LRS and ZRS stay within a single region." },
    { type: "multi", cat: "arch", topic: "a_network", q: "Which TWO Azure services can connect an on-premises network to an Azure virtual network? (Choose two.)", options: ["VNet peering", "Azure VPN Gateway", "Azure ExpressRoute", "Azure DNS"], answers: [1, 2], explain: "VPN Gateway (encrypted over the internet) and ExpressRoute (private dedicated link) connect on-premises to Azure. VNet peering connects two Azure VNets; Azure DNS is name resolution." },
    { type: "multi", cat: "govern", topic: "g_gov", q: "Which TWO tasks can Azure Policy perform? (Choose two.)", options: ["Restrict the regions where resources can be deployed", "Require specific tags on resources", "Grant a user permission to manage a resource group", "Provision new virtual machines on a schedule"], answers: [0, 1], explain: "Azure Policy enforces compliance rules such as allowed regions and required tags. Granting permissions is RBAC; it does not provision resources." },
    { type: "multi", cat: "govern", topic: "g_monitor", q: "Which TWO capabilities are part of Azure Monitor? (Choose two.)", options: ["Log Analytics", "Application Insights", "Azure Policy", "Service Trust Portal"], answers: [0, 1], explain: "Log Analytics and Application Insights are features of Azure Monitor. Azure Policy is governance; the Service Trust Portal hosts compliance documents." },
    { type: "multi", cat: "cloud", topic: "c_shared", q: "Under the shared responsibility model, which TWO items are ALWAYS the customer's responsibility regardless of service type? (Choose two.)", options: ["Information and data", "Accounts and identities", "Physical datacenter security", "The physical network"], answers: [0, 1], explain: "Data and accounts/identities are always the customer's responsibility. Physical datacenter and network are always the provider's." },
    { type: "multi", cat: "govern", topic: "g_cost", q: "Which TWO factors directly affect the cost of an Azure resource? (Choose two.)", options: ["The Azure region where it is deployed", "The amount of outbound (egress) data transfer", "The colour theme of the Azure portal", "The day of the week"], answers: [0, 1], explain: "Region and outbound data transfer affect cost. The portal theme and day of week do not." },
    { type: "multi", cat: "cloud", topic: "c_models", q: "Which TWO statements are characteristics of the public cloud model? (Choose two.)", options: ["Resources are multi-tenant and shared", "There is no capital expenditure (CapEx) required", "Hardware is dedicated to a single organization", "It must be hosted in your own datacenter"], answers: [0, 1], explain: "Public cloud is multi-tenant with no CapEx. Dedicated hardware and on-premises hosting describe a private cloud." },
    { type: "multi", cat: "arch", topic: "a_core", q: "Which TWO scopes sit ABOVE a resource group in the Azure management hierarchy? (Choose two.)", options: ["Subscriptions", "Management groups", "Individual resources", "Network interface cards"], answers: [0, 1], explain: "The hierarchy is Management groups → Subscriptions → Resource groups → Resources, so subscriptions and management groups are above a resource group." },
    { type: "multi", cat: "arch", topic: "a_identity", q: "Which TWO are valid authentication factors for multi-factor authentication (MFA)? (Choose two.)", options: ["Something you know (a password)", "Something you have (a phone or token)", "Your job title", "Your office floor number"], answers: [0, 1], explain: "MFA combines factors such as something you know, something you have, or something you are. A job title or floor number are not authentication factors." },

    /* ---------- YES / NO (case-study style) ---------- */
    { type: "yesno", cat: "arch", topic: "a_storage", q: "Your company needs to protect data in an Azure Storage account against a complete regional outage. Proposed solution: Configure the storage account to use locally redundant storage (LRS). Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. LRS only replicates within a single datacenter and does not protect against a regional outage. GRS or GZRS would meet the goal." },
    { type: "yesno", cat: "arch", topic: "a_storage", q: "Your company needs to protect data in an Azure Storage account against a complete regional outage. Proposed solution: Configure the storage account to use geo-redundant storage (GRS). Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. GRS replicates data to a paired secondary region, protecting against a regional outage." },
    { type: "yesno", cat: "cloud", topic: "c_types", q: "A development team wants to host a web app without managing the operating system or runtime. Proposed solution: Deploy the app to Azure Virtual Machines. Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. Azure Virtual Machines (IaaS) still require you to manage the OS. Azure App Service (PaaS) would meet the goal." },
    { type: "yesno", cat: "arch", topic: "a_identity", q: "You must require multi-factor authentication only when users sign in from an unfamiliar location. Proposed solution: Implement Microsoft Entra Conditional Access. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. Conditional Access can require MFA based on signals such as sign-in location." },
    { type: "yesno", cat: "govern", topic: "g_gov", q: "You must prevent a resource from being accidentally deleted while still allowing administrators to modify it. Proposed solution: Apply a ReadOnly lock to the resource. Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. A ReadOnly lock also blocks modifications. A CanNotDelete (Delete) lock would meet the goal." },
    { type: "yesno", cat: "arch", topic: "a_core", q: "You must protect an application against the failure of a single datacenter within an Azure region. Proposed solution: Deploy the application across Availability Zones. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. Availability Zones are physically separate datacenters within a region, protecting against a datacenter-level failure." },
    { type: "yesno", cat: "govern", topic: "g_cost", q: "You need to estimate the cost of a planned Azure solution before deploying it. Proposed solution: Use the Total Cost of Ownership (TCO) Calculator. Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. The TCO Calculator compares on-premises vs Azure costs. The Pricing Calculator estimates the cost of a planned deployment." },
    { type: "yesno", cat: "cloud", topic: "c_models", q: "A company wants to run their existing VMware workloads natively in Azure without re-architecting them. Proposed solution: Use Azure VMware Solution. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. Azure VMware Solution runs native VMware environments directly on Azure infrastructure." },

    /* ---------- COMPLETE THE SENTENCE (dropdowns) ---------- */
    { type: "sentence", cat: "cloud", topic: "c_types", segments: ["", { options: ["IaaS", "PaaS", "SaaS"], answer: 0 }, " gives the customer the most control over the operating system, while ", { options: ["IaaS", "PaaS", "SaaS"], answer: 2 }, " gives the least."], explain: "IaaS gives the most control (you manage the OS); SaaS gives the least (you just use the software)." },
    { type: "sentence", cat: "arch", topic: "a_storage", segments: ["The ", { options: ["Hot", "Cool", "Archive"], answer: 2 }, " access tier offers the lowest storage cost for rarely accessed data."], explain: "The Archive tier has the lowest storage cost for rarely accessed, long-term data (retrieval requires rehydration)." },
    { type: "sentence", cat: "arch", topic: "a_core", segments: ["", { options: ["Availability Zones", "Region pairs"], answer: 0 }, " protect against a datacenter failure within a region, while ", { options: ["Availability Zones", "Region pairs"], answer: 1 }, " protect against a full regional outage."], explain: "Availability Zones protect within a region; region pairs provide cross-region disaster recovery." },
    { type: "sentence", cat: "govern", topic: "g_monitor", segments: ["", { options: ["Azure Advisor", "Azure Service Health"], answer: 1 }, " reports outages and maintenance of Azure itself, while ", { options: ["Azure Advisor", "Azure Service Health"], answer: 0 }, " provides personalized best-practice recommendations."], explain: "Service Health reports the health of Azure; Advisor recommends improvements to your resources." },
    { type: "sentence", cat: "cloud", topic: "c_cost", segments: ["Buying physical servers upfront is an example of ", { options: ["CapEx", "OpEx"], answer: 0 }, ", while paying for cloud resources as you use them is an example of ", { options: ["CapEx", "OpEx"], answer: 1 }, "."], explain: "Upfront capital purchases are CapEx; ongoing consumption-based spending is OpEx." },
    { type: "sentence", cat: "arch", topic: "a_identity", segments: ["", { options: ["Authentication", "Authorization"], answer: 0 }, " proves who you are, while ", { options: ["Authentication", "Authorization"], answer: 1 }, " determines what you are allowed to access."], explain: "Authentication (AuthN) verifies identity; authorization (AuthZ) determines access rights." },

  ];

  window.AZ_QUESTIONS = (window.AZ_QUESTIONS || []).concat(extra);
})();
