/* =====================================================================
   SC-200 Study Hub — alternate exam question formats
   Adds the styles the real SC-200 uses beyond single-answer:
     • "multi"    — multiple-response ("choose two/three"); answers is an array
     • "yesno"    — case-study style statement answered Yes/No
     • "sentence" — "complete the sentence" with one or more dropdowns

   Loaded AFTER js/questions.js and BEFORE js/data.js, appending to the
   shared AZ_QUESTIONS pool so the mock tests pick them up automatically.
   ===================================================================== */
(function () {
  const extra = [

    /* ---------- MULTIPLE RESPONSE (choose two/three) ---------- */
    { type: "multi", cat: "xdr", topic: "x_endpoint", q: "Which TWO of the following are response actions available on a device in Microsoft Defender for Endpoint? (Choose two.)", options: ["Isolate the device", "Collect an investigation package", "Enable a Defender for Cloud plan", "Create a Sentinel watchlist"], answers: [0, 1], explain: "Isolating a device and collecting an investigation package are MDE device response actions. Defender plans and watchlists are unrelated features." },
    { type: "multi", cat: "xdr", topic: "x_office", q: "Which TWO Microsoft Defender for Office 365 features help protect against malicious URLs and attachments? (Choose two.)", options: ["Safe Links", "Safe Attachments", "Just-in-time VM access", "File Integrity Monitoring"], answers: [0, 1], explain: "Safe Links (URL time-of-click scanning) and Safe Attachments (sandbox detonation) protect email/collaboration. JIT and FIM are Defender for Cloud features." },
    { type: "multi", cat: "xdr", topic: "x_hunting", q: "Which TWO tables would you join in Defender XDR advanced hunting to link an alert to its associated entities? (Choose two.)", options: ["AlertInfo", "AlertEvidence", "SecurityIncident", "Heartbeat"], answers: [0, 1], explain: "AlertInfo (alert metadata) and AlertEvidence (entities/evidence) are joined to relate alerts to files, IPs, and accounts." },
    { type: "multi", cat: "cloud", topic: "c_plans", q: "Which TWO capabilities are provided by Defender for Servers in Microsoft Defender for Cloud? (Choose two.)", options: ["Just-in-time (JIT) VM access", "File Integrity Monitoring (FIM)", "Safe Attachments", "TAXII threat feed ingestion"], answers: [0, 1], explain: "Defender for Servers provides JIT VM access and File Integrity Monitoring. Safe Attachments is Office 365; TAXII ingestion is Sentinel TI." },
    { type: "multi", cat: "cloud", topic: "c_cspm", q: "Which TWO statements about Microsoft Defender for Cloud are correct? (Choose two.)", options: ["Foundational CSPM (recommendations + Secure Score) is free", "It can protect AWS and GCP workloads via multicloud connectors", "Workload protection (Defender plans) is always free", "It replaces Microsoft Sentinel"], answers: [0, 1], explain: "Foundational CSPM is free and multicloud (AWS/GCP) is supported. Defender plans (CWPP) are paid, and it complements — not replaces — Sentinel." },
    { type: "multi", cat: "sentinel", topic: "s_analytics", q: "Which TWO are valid analytics rule types in Microsoft Sentinel? (Choose two.)", options: ["Scheduled", "Fusion", "Playbook", "Workbook"], answers: [0, 1], explain: "Scheduled and Fusion are analytics rule types. Playbooks are automation (Logic Apps) and workbooks are visualizations." },
    { type: "multi", cat: "sentinel", topic: "s_soar", q: "Which TWO actions can a Microsoft Sentinel automation rule perform? (Choose two.)", options: ["Run a playbook", "Assign an incident to an owner", "Onboard a device to Defender for Endpoint", "Create a Log Analytics workspace"], answers: [0, 1], explain: "Automation rules can run playbooks and manage incidents (assign, change status, tag). They don't onboard devices or create workspaces." },
    { type: "multi", cat: "sentinel", topic: "s_connectors", q: "Which TWO methods are used to bring data into Microsoft Sentinel? (Choose two.)", options: ["Data connectors (e.g., Microsoft Entra ID)", "CEF/Syslog via the Azure Monitor Agent", "Attack Surface Reduction rules", "Just-in-time VM access"], answers: [0, 1], explain: "Data connectors and CEF/Syslog via AMA ingest data into Sentinel. ASR and JIT are protection features, not ingestion." },
    { type: "multi", cat: "sentinel", topic: "s_kql", q: "Which TWO KQL operators are used to aggregate and to filter data, respectively? (Choose two.)", options: ["summarize (aggregate)", "where (filter)", "render (aggregate)", "isolate (filter)"], answers: [0, 1], explain: "summarize aggregates rows into groups; where filters rows by a condition. render only visualizes; isolate is not KQL." },
    { type: "multi", cat: "xdr", topic: "x_incidents", q: "Which TWO are true about incidents in Microsoft Defender XDR? (Choose two.)", options: ["An incident correlates multiple related alerts", "Incidents can be classified as true or false positive", "An incident is a single raw log entry", "Incidents can only be viewed in the Azure portal"], answers: [0, 1], explain: "Incidents correlate related alerts and can be classified true/false positive. They're managed in the Microsoft Defender portal, not the Azure portal." },

    /* ---------- YES / NO (case-study style) ---------- */
    { type: "yesno", cat: "xdr", topic: "x_endpoint", q: "You need to immediately stop a compromised device from communicating on the network while keeping it manageable for investigation. Proposed solution: Isolate the device in Microsoft Defender for Endpoint. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. Device isolation cuts network communication (except the Defender service) while the device stays available for investigation." },
    { type: "yesno", cat: "xdr", topic: "x_identity", q: "You must detect Pass-the-Ticket and DCSync attacks against on-premises Active Directory. Proposed solution: Deploy Microsoft Defender for Cloud Apps. Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. On-premises AD attacks are detected by Microsoft Defender for Identity (sensors on domain controllers), not Defender for Cloud Apps (a CASB)." },
    { type: "yesno", cat: "cloud", topic: "c_plans", q: "You must reduce brute-force RDP attacks by keeping management ports closed until access is requested and approved. Proposed solution: Enable just-in-time (JIT) VM access in Microsoft Defender for Cloud. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. JIT VM access keeps RDP/SSH ports closed and opens them only on approved, time-limited requests." },
    { type: "yesno", cat: "sentinel", topic: "s_analytics", q: "You need Microsoft Defender for Cloud alerts to automatically create incidents in Microsoft Sentinel. Proposed solution: Create a Fusion analytics rule. Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. Use a Microsoft Security analytics rule to create incidents from Microsoft security product alerts. Fusion detects multistage attacks via ML." },
    { type: "yesno", cat: "sentinel", topic: "s_soar", q: "You want to automatically run a workflow that blocks a user and notifies the SOC whenever a high-severity incident is created in Sentinel. Proposed solution: Create a playbook and trigger it from an automation rule. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. A playbook (Logic App) performs the actions, and an automation rule triggers it on qualifying incidents." },
    { type: "yesno", cat: "sentinel", topic: "s_workspace", q: "An analyst must triage and close Sentinel incidents but must not be able to create analytics rules or connectors. Proposed solution: Grant the Microsoft Sentinel Reader role. Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. Reader is view-only and cannot manage incidents. The Microsoft Sentinel Responder role allows managing incidents without editing content." },
    { type: "yesno", cat: "xdr", topic: "x_office", q: "Malicious phishing emails were delivered to inboxes before being identified. You need them removed automatically now that they're known-bad. Proposed solution: Rely on Zero-hour Auto Purge (ZAP). Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. ZAP retroactively removes malicious/phishing messages already delivered once they are identified." },
    { type: "yesno", cat: "cloud", topic: "c_cspm", q: "You want a free way to continuously assess Azure resource configurations against best practices and track improvement over time. Proposed solution: Use foundational CSPM and Secure Score in Microsoft Defender for Cloud. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. Foundational CSPM (recommendations + Secure Score) is free and continuously assesses posture." },

    /* ---------- COMPLETE THE SENTENCE (dropdowns) ---------- */
    { type: "sentence", cat: "xdr", topic: "x_incidents", segments: ["In Microsoft Defender XDR, a single detection is an ", { options: ["alert", "incident"], answer: 0 }, ", while a correlated group of related detections is an ", { options: ["alert", "incident"], answer: 1 }, "."], explain: "An alert is one detection; an incident correlates multiple related alerts into the story of an attack." },
    { type: "sentence", cat: "sentinel", topic: "s_soar", segments: ["In Microsoft Sentinel, a ", { options: ["playbook", "workbook"], answer: 0 }, " automates response actions, while a ", { options: ["playbook", "workbook"], answer: 1 }, " provides interactive visualizations."], explain: "Playbooks (Logic Apps) automate response; workbooks visualize data." },
    { type: "sentence", cat: "sentinel", topic: "s_analytics", segments: ["A ", { options: ["Scheduled", "Near-real-time (NRT)"], answer: 1 }, " analytics rule runs about once per minute for the fastest detection, while a ", { options: ["Scheduled", "Near-real-time (NRT)"], answer: 0 }, " rule runs on a defined interval you set."], explain: "NRT rules run ~every minute; Scheduled rules run on the interval you configure." },
    { type: "sentence", cat: "cloud", topic: "c_cspm", segments: ["In Defender for Cloud, ", { options: ["CSPM", "CWPP"], answer: 0 }, " assesses configuration posture and produces Secure Score, while ", { options: ["CSPM", "CWPP"], answer: 1 }, " (the Defender plans) provides workload threat protection."], explain: "CSPM = posture management (free foundational); CWPP = workload protection via paid Defender plans." },
    { type: "sentence", cat: "sentinel", topic: "s_kql", segments: ["In KQL, ", { options: ["project", "extend"], answer: 1 }, " adds a new calculated column, while ", { options: ["project", "extend"], answer: 0 }, " selects a specific subset of columns."], explain: "extend adds a computed column; project selects/renames columns and drops the rest." },
    { type: "sentence", cat: "xdr", topic: "x_identity", segments: ["", { options: ["Defender for Identity", "Entra ID Protection"], answer: 0 }, " detects threats against on-premises Active Directory, while ", { options: ["Defender for Identity", "Entra ID Protection"], answer: 1 }, " detects risky sign-ins and users for cloud identities."], explain: "Defender for Identity = on-prem AD threats; Entra ID Protection = cloud identity risk." },

  ];

  window.AZ_QUESTIONS = (window.AZ_QUESTIONS || []).concat(extra);
})();
