/* =====================================================================
   SC-200 Study Hub — supplementary question bank
   Deeper and edge-case coverage across every topic (incl. more KQL and
   more alternate formats) so the course is comprehensive enough to pass.

   Loaded AFTER js/questions.js and js/questions-formats.js, appending to
   the shared AZ_QUESTIONS pool. Each item:
     single/yesno : { cat, topic, q, options[], answer, explain }
     multi        : { type:"multi", ..., answers:[...] }
     sentence     : { type:"sentence", ..., segments:[...] }
   ===================================================================== */
(function () {
  const extra = [

  /* ================= DEFENDER XDR ================= */

  /* --- Endpoint --- */
  { cat: "xdr", topic: "x_endpoint", q: "You need to stop attackers or malicious apps from disabling Microsoft Defender Antivirus and changing its security settings on managed devices. Which feature should you enable?", options: ["Tamper protection", "Controlled folder access", "Network protection", "Web content filtering"], answer: 0, explain: "Tamper protection prevents unauthorized changes (including by malware) to Defender Antivirus settings and real-time protection." },
  { cat: "xdr", topic: "x_endpoint", q: "A company wants to protect specific folders from unauthorized modification by ransomware. Which Microsoft Defender for Endpoint capability should they enable?", options: ["Controlled folder access", "Attack surface reduction rules only", "Tamper protection", "Live response"], answer: 0, explain: "Controlled folder access blocks untrusted apps from modifying protected folders, mitigating ransomware." },
  { cat: "xdr", topic: "x_endpoint", q: "You want to block outbound connections from devices to low-reputation or malicious domains and IP addresses at the OS level. Which MDE feature provides this?", options: ["Network protection", "Safe Links", "Just-in-time access", "Controlled folder access"], answer: 0, explain: "Network protection blocks connections to dangerous domains/IPs, extending SmartScreen-style protection to the OS/network layer." },
  { cat: "xdr", topic: "x_endpoint", q: "Your organization uses a non-Microsoft antivirus as primary protection but wants Defender for Endpoint to remediate malicious artifacts it detects behind the scenes. What should you enable?", options: ["EDR in block mode", "Passive mode with no action", "Tamper protection", "Controlled folder access"], answer: 0, explain: "EDR in block mode lets Defender for Endpoint remediate post-breach artifacts even when a third-party AV is the primary product." },
  { cat: "xdr", topic: "x_endpoint", q: "An admin wants automated investigations to fully remediate malicious artifacts on a set of devices without requiring analyst approval. What should they configure?", options: ["Set the device group's automation level to Full - remediate threats automatically", "Disable automated investigation", "Isolate all devices", "Set automation to No automated response"], answer: 0, explain: "The device group automation level controls AIR behavior; 'Full' remediates automatically, while semi-automated levels require approval." },
  { cat: "xdr", topic: "x_endpoint", q: "You need to dynamically group devices (for example, by tag or OS) so that RBAC and automation apply to the right machines. What should you use?", options: ["Device groups (with tags/rules)", "Watchlists", "Data collection rules", "Analytics rules"], answer: 0, explain: "Device groups (using rules and device tags) scope permissions and automation to matching devices in Defender for Endpoint." },

  /* --- Office 365 --- */
  { cat: "xdr", topic: "x_office", q: "A user reports a phishing email that Defender for Office 365 did not catch. You want Microsoft to analyze it and improve detection. What should you do in the Defender portal?", options: ["Create an admin submission (Submissions)", "Add a Safe Links policy", "Create an ASR rule", "Open a JIT request"], answer: 0, explain: "Admin submissions send suspected missed phish/malware (or false positives) to Microsoft for analysis and tuning." },
  { cat: "xdr", topic: "x_office", q: "A security team wants to measure how susceptible employees are to phishing and deliver targeted training. Which Defender for Office 365 feature should they use?", options: ["Attack simulation training", "Zero-hour Auto Purge", "Configuration analyzer", "Threat analytics"], answer: 0, explain: "Attack simulation training runs realistic phishing simulations and assigns training based on user behavior." },
  { cat: "xdr", topic: "x_office", q: "An admin wants to compare their existing email security policies against Microsoft's recommended Standard and Strict settings and see where they fall short. Which tool should they use?", options: ["Configuration analyzer", "Threat Explorer", "Tenant Allow/Block List", "Action center"], answer: 0, explain: "The configuration analyzer compares your policy settings to the Standard/Strict presets and highlights differences to remediate." },
  { cat: "xdr", topic: "x_office", q: "Which Defender for Office 365 policy protects high-value users from impersonation and spoofing using mailbox intelligence?", options: ["Anti-phishing policy", "Anti-malware policy", "Safe Attachments policy", "Outbound spam policy"], answer: 0, explain: "The anti-phishing policy provides user/domain impersonation and spoof protection, using mailbox intelligence." },
  { cat: "xdr", topic: "x_office", q: "Where do admins review and release messages that Defender for Office 365 held as malicious or spam, subject to quarantine policies?", options: ["Quarantine", "Action center", "Threat analytics", "Secure Score"], answer: 0, explain: "Quarantine (governed by quarantine policies) is where held messages are reviewed, released, or reported." },

  /* --- Identity --- */
  { cat: "xdr", topic: "x_identity", q: "A SOC wants Defender for Identity to alert immediately if a specific decoy 'honeytoken' account is ever used, since no legitimate activity should touch it. What should they configure?", options: ["Tag the account as a honeytoken (sensitive) entity", "Disable the account", "Add it to a watchlist", "Create a Safe Links policy"], answer: 0, explain: "Tagging accounts as honeytoken/sensitive in Defender for Identity raises high-value alerts on any activity involving them." },
  { cat: "xdr", topic: "x_identity", q: "Defender for Identity provides recommendations to reduce your on-premises identity attack surface (e.g., legacy protocols, unsecure configurations). What are these called?", options: ["Identity security posture assessments", "Attack surface reduction rules", "Governance rules", "Data collection rules"], answer: 0, explain: "Identity security posture assessments highlight risky AD configurations and how to remediate them." },
  { cat: "xdr", topic: "x_identity", q: "Defender for Identity raises an alert indicating a Golden Ticket attack. Which attack phase does this represent?", options: ["Domain dominance", "Reconnaissance", "Initial access", "Delivery"], answer: 0, explain: "Golden Ticket (forged Kerberos TGT) is a domain-dominance technique giving persistent, privileged access." },
  { cat: "xdr", topic: "x_identity", q: "From a Defender XDR incident involving a compromised on-premises account, an analyst wants to disable the user in Active Directory as a response. What enables this action?", options: ["Defender for Identity action accounts with the required AD permissions", "A Sentinel watchlist", "A Safe Attachments policy", "EDR in block mode"], answer: 0, explain: "Defender for Identity remediation actions (like disable user) require configured action accounts with permissions in AD." },

  /* --- Cloud Apps --- */
  { cat: "xdr", topic: "x_mda", q: "A company wants to detect and manage risky OAuth applications that users have consented to in their Microsoft 365 tenant. Which capability should they use?", options: ["App governance in Defender for Cloud Apps", "Cloud Discovery", "Safe Links", "JIT VM access"], answer: 0, explain: "App governance (in Defender for Cloud Apps) monitors and governs OAuth apps and their permissions/behavior for risk." },
  { cat: "xdr", topic: "x_mda", q: "A team wants Defender for Cloud Apps to automatically apply a governance action — like quarantining a file or removing external sharing — when a file policy is violated. What should they configure?", options: ["Governance actions on a file policy", "A DCR", "A Fusion rule", "Tamper protection"], answer: 0, explain: "File policies in Defender for Cloud Apps can trigger governance actions such as quarantine or removing sharing on matching files." },
  { cat: "xdr", topic: "x_mda", q: "To get Cloud Discovery data continuously from managed endpoints without manually uploading firewall logs, which integration should you enable?", options: ["Integrate Defender for Cloud Apps with Defender for Endpoint", "Deploy a Defender for Identity sensor", "Enable Defender for DNS", "Create a Sentinel workbook"], answer: 0, explain: "Integrating Defender for Cloud Apps with Defender for Endpoint provides endpoint-based Cloud Discovery without a manual log upload." },
  { cat: "xdr", topic: "x_mda", q: "Defender for Cloud Apps can classify and protect sensitive files in connected apps by leveraging which Microsoft data-protection technology?", options: ["Microsoft Purview Information Protection sensitivity labels", "Attack surface reduction", "Just-in-time access", "Fusion"], answer: 0, explain: "Defender for Cloud Apps integrates with Microsoft Purview Information Protection to detect and label/protect sensitive content." },

  /* --- XDR incidents & posture --- */
  { cat: "xdr", topic: "x_incidents", q: "A CISO wants a single score, with prioritized improvement actions, that measures the security posture of the organization's Microsoft 365 identities, devices, apps, and data. Which should they use?", options: ["Microsoft Secure Score (in the Defender portal)", "Secure Score in Defender for Cloud", "Sentinel workbook", "Threat analytics"], answer: 0, explain: "Microsoft Secure Score (Defender portal) measures M365 security posture with improvement actions; Defender for Cloud's Secure Score covers cloud resources." },
  { cat: "xdr", topic: "x_incidents", q: "An analyst wants Microsoft's up-to-date reports on active threat campaigns and threat actors, including the organization's exposure and recommended mitigations. Which Defender XDR feature provides this?", options: ["Threat analytics", "Advanced hunting", "Action center", "Attack simulation training"], answer: 0, explain: "Threat analytics provides threat intelligence reports on campaigns/actors with your exposure and recommended actions." },
  { cat: "xdr", topic: "x_incidents", q: "Where in the Microsoft Defender portal do analysts review, approve, and track the history of automated and manual remediation actions?", options: ["Action center", "Secure Score", "Threat analytics", "Content hub"], answer: 0, explain: "The Action center centralizes pending and completed remediation actions across Defender XDR for approval and tracking." },
  { cat: "xdr", topic: "x_incidents", q: "A specific benign alert keeps firing for a known internal tool. You want to reduce this noise without disabling the detection entirely. What should you create?", options: ["An alert tuning rule (suppression) with conditions", "A new incident", "A Fusion rule", "A data connector"], answer: 0, explain: "Alert tuning/suppression rules let you automatically resolve or hide specific benign alerts based on conditions." },
  { cat: "xdr", topic: "x_incidents", q: "A security manager wants to grant analysts granular, role-based permissions across Defender for Endpoint, Office 365, and Identity from one place. Which capability should they use?", options: ["Microsoft Defender XDR Unified RBAC", "Azure Policy", "Just-in-time access", "Watchlists"], answer: 0, explain: "Microsoft Defender XDR Unified role-based access control provides centralized, granular permissions across the XDR workloads." },

  /* --- Advanced hunting --- */
  { cat: "xdr", topic: "x_hunting", q: "When creating a custom detection rule from an advanced hunting query, which of the following can it do automatically when it matches?", options: ["Take response actions such as isolate device, run AV scan, or block a file", "Only send an email", "Delete the underlying logs", "Change the workspace retention"], answer: 0, explain: "Custom detection rules can trigger response actions (isolate device, run AV scan, collect package, block/quarantine file) in addition to raising alerts." },
  { cat: "xdr", topic: "x_hunting", q: "How often can a Microsoft Defender XDR custom detection rule be configured to run?", options: ["On a frequency such as continuous (near real time), every hour, 3 hours, 12 hours, or 24 hours", "Only once per week", "Only manually", "Only at midnight"], answer: 0, explain: "Custom detection rules support frequencies from continuous/near-real-time up to every 24 hours." },
  { cat: "xdr", topic: "x_hunting", q: "In advanced hunting, an analyst finds malicious files in query results and wants to remediate them directly from the results grid. What can they use?", options: ["The 'Take actions' option on the query results", "A Sentinel playbook only", "A Defender for Cloud recommendation", "A DCR"], answer: 0, explain: "Advanced hunting lets you select records and 'Take actions' (e.g., isolate device, quarantine file) directly from results." },
  { cat: "xdr", topic: "x_hunting", q: "Which advanced hunting table provides device metadata such as operating system, version, and onboarding status?", options: ["DeviceInfo", "DeviceProcessEvents", "EmailEvents", "AlertEvidence"], answer: 0, explain: "DeviceInfo holds device metadata (OS, version, onboarding); process telemetry is in DeviceProcessEvents." },
  { cat: "xdr", topic: "x_hunting", q: "An analyst hunting on-premises AD activity (group membership changes, account modifications) in Defender XDR should query which table?", options: ["IdentityDirectoryEvents", "CloudAppEvents", "DeviceNetworkEvents", "EmailUrlInfo"], answer: 0, explain: "IdentityDirectoryEvents captures on-premises AD directory activities surfaced by Defender for Identity." },
  { cat: "xdr", topic: "x_hunting", q: "An analyst wants to reuse a complex KQL logic block across multiple advanced hunting queries. What should they create?", options: ["A saved query / function", "A watchlist", "A workbook", "A DCR"], answer: 0, explain: "Saved queries (and functions) let analysts reuse KQL logic across advanced hunting sessions." },

  /* ================= DEFENDER FOR CLOUD ================= */

  /* --- CSPM --- */
  { cat: "cloud", topic: "c_cspm", q: "A team wants advanced posture features like attack path analysis, the cloud security explorer, and agentless machine scanning. Which offering provides these?", options: ["The Defender Cloud Security Posture Management (Defender CSPM) plan", "Foundational (free) CSPM", "Defender for DNS", "Microsoft Sentinel"], answer: 0, explain: "The paid Defender CSPM plan adds attack path analysis, the cloud security explorer, agentless scanning, and more beyond the free foundational CSPM." },
  { cat: "cloud", topic: "c_cspm", q: "A company wants a security policy applied consistently across many subscriptions in Microsoft Defender for Cloud. At which scope should they assign the security initiative?", options: ["A management group", "A single resource", "A storage account", "A device group"], answer: 0, explain: "Assigning the initiative at a management group applies the policy to all subscriptions beneath it consistently." },
  { cat: "cloud", topic: "c_cspm", q: "A resource legitimately can't meet a specific recommendation and you want to stop it affecting your Secure Score without turning off the recommendation for everyone. What should you create?", options: ["An exemption for that resource/recommendation", "A new Defender plan", "A watchlist", "A DCR"], answer: 0, explain: "Exemptions exclude specific resources from a recommendation (with justification) so they don't impact Secure Score." },
  { cat: "cloud", topic: "c_cspm", q: "A security lead wants each recommendation assigned to an owner with a remediation due date and accountability tracking. Which Defender for Cloud feature should they use?", options: ["Governance rules", "Just-in-time access", "Continuous export", "Threat analytics"], answer: 0, explain: "Governance rules assign owners and due dates to recommendations, driving accountability for remediation." },
  { cat: "cloud", topic: "c_cspm", q: "A SOC wants Defender for Cloud alerts and recommendations streamed continuously to a Log Analytics workspace or Event Hub for retention and integration. What should they configure?", options: ["Continuous export", "A watchlist", "An ASR rule", "A quarantine policy"], answer: 0, explain: "Continuous export sends Defender for Cloud alerts/recommendations/secure score to Log Analytics or Event Hubs on an ongoing basis." },

  /* --- Plans --- */
  { cat: "cloud", topic: "c_plans", q: "Which Defender for Servers plan includes file integrity monitoring, just-in-time VM access, and OS-level threat detection (versus the more basic plan)?", options: ["Defender for Servers Plan 2", "Defender for Servers Plan 1", "Defender for Storage", "Foundational CSPM"], answer: 0, explain: "Defender for Servers Plan 2 adds FIM, JIT, threat detection, and a free data ingestion allowance; Plan 1 focuses on MDE integration." },
  { cat: "cloud", topic: "c_plans", q: "A company wants vulnerability assessment of their Azure VMs integrated into Defender for Cloud recommendations. Which solution provides this by default with Defender for Servers?", options: ["Microsoft Defender Vulnerability Management", "Safe Attachments", "Fusion", "UEBA"], answer: 0, explain: "Defender for Servers integrates Microsoft Defender Vulnerability Management to assess and surface VM vulnerabilities." },
  { cat: "cloud", topic: "c_plans", q: "Which Defender plan detects anomalous access to secrets, keys, and certificates that may indicate compromise?", options: ["Defender for Key Vault", "Defender for DNS", "Defender for Storage", "Defender for App Service"], answer: 0, explain: "Defender for Key Vault detects unusual or suspicious access attempts to Key Vault secrets/keys/certificates." },
  { cat: "cloud", topic: "c_plans", q: "Which Defender plan helps detect data exfiltration and communication with malicious domains by monitoring name-resolution traffic?", options: ["Defender for DNS", "Defender for SQL", "Defender for Containers", "Defender for Resource Manager"], answer: 0, explain: "Defender for DNS analyzes DNS queries to detect exfiltration, malware C2, and other DNS-based threats." },
  { cat: "cloud", topic: "c_plans", q: "Defender for Cloud increasingly relies on which agent to collect security data from Azure and Arc-enabled servers, replacing the legacy Log Analytics (MMA) agent?", options: ["Azure Monitor Agent (AMA)", "Microsoft Monitoring Agent", "The Sentinel forwarder only", "No agent is used"], answer: 0, explain: "The Azure Monitor Agent (AMA) is the current agent; the legacy Log Analytics/MMA agent has been retired." },
  { cat: "cloud", topic: "c_plans", q: "Which Defender plan protects Azure SQL databases by detecting anomalous activities such as SQL injection and unusual access patterns?", options: ["Defender for SQL", "Defender for Storage", "Defender for Key Vault", "Defender for DNS"], answer: 0, explain: "Defender for SQL provides threat detection (e.g., SQL injection, anomalous access) and vulnerability assessment for databases." },

  /* --- Compliance --- */
  { cat: "cloud", topic: "c_compliance", q: "A regulated company must track compliance against a standard not shown by default in Defender for Cloud. What should they do?", options: ["Add the standard (custom or built-in) to the regulatory compliance dashboard", "Disable Defender for Cloud", "Use only Secure Score", "Create a Sentinel playbook"], answer: 0, explain: "You can add built-in or custom standards to the regulatory compliance dashboard (a paid Defender plan is generally required)." },
  { cat: "cloud", topic: "c_compliance", q: "Which Defender for Cloud view shows how your Azure environment maps to controls of standards like PCI-DSS and NIST — as opposed to Microsoft Purview Compliance Manager?", options: ["The regulatory compliance dashboard", "Threat analytics", "Advanced hunting", "The Action center"], answer: 0, explain: "The regulatory compliance dashboard in Defender for Cloud maps resource posture to standard controls; Compliance Manager (Purview) is a separate, broader tool." },
  { cat: "cloud", topic: "c_compliance", q: "To generate an audit report of your current control status from the regulatory compliance dashboard, what can you do?", options: ["Download a compliance report (e.g., PDF/CSV) from the dashboard", "Delete failing controls", "Turn off Secure Score", "Create a DCR"], answer: 0, explain: "The regulatory compliance dashboard lets you download reports/certifications and export status for auditors." },

  /* ================= MICROSOFT SENTINEL ================= */

  /* --- Workspace & Roles --- */
  { cat: "sentinel", topic: "s_workspace", q: "A managed security provider needs to query and manage Microsoft Sentinel across many customers' workspaces from one place. Which capability supports this?", options: ["Azure Lighthouse (cross-workspace / cross-tenant management)", "A single shared workspace for all customers", "Watchlists", "Fusion"], answer: 0, explain: "Azure Lighthouse enables cross-tenant management, letting an MSSP work across multiple customer Sentinel workspaces; cross-workspace queries use the workspace() function." },
  { cat: "sentinel", topic: "s_workspace", q: "You want to reduce cost for a high-volume, low-security-value log source while keeping it queryable for a limited time. Which Log Analytics table plan should you use?", options: ["Basic logs", "Analytics logs", "Archive only", "Auxiliary is not supported"], answer: 0, explain: "The Basic logs plan lowers ingestion cost for high-volume/low-value data, with limited query features and shorter interactive retention than Analytics logs." },
  { cat: "sentinel", topic: "s_workspace", q: "You must keep security data queryable for interactive analysis for 90 days but retain it cheaply for 2 years for compliance. What should you configure?", options: ["Interactive (analytics) retention plus long-term archive retention", "Delete data after 90 days", "Use Basic logs for everything", "Increase the commitment tier only"], answer: 0, explain: "Set interactive retention for active querying and configure archive/long-term retention (total retention) for cheap compliance storage; archived data is accessed via search jobs/restore." },
  { cat: "sentinel", topic: "s_workspace", q: "Which built-in Microsoft Sentinel role allows creating and editing analytics rules, workbooks, and other content but is scoped to Sentinel (not full subscription ownership)?", options: ["Microsoft Sentinel Contributor", "Microsoft Sentinel Reader", "Microsoft Sentinel Responder", "Owner"], answer: 0, explain: "Microsoft Sentinel Contributor can create/edit Sentinel content (rules, workbooks) without broad subscription ownership." },

  /* --- Connectors & ingestion --- */
  { cat: "sentinel", topic: "s_connectors", q: "A vendor's REST API has no built-in Sentinel connector. You want to build one without writing/hosting custom code. Which approach should you use?", options: ["The Codeless Connector Platform (CCP)", "A Fusion rule", "A watchlist", "An ASR rule"], answer: 0, explain: "The Codeless Connector Platform lets you build custom data connectors declaratively, without deploying code." },
  { cat: "sentinel", topic: "s_connectors", q: "You need to aggregate very high-volume raw logs into summarized results on a schedule to cut query cost and speed up detections. Which Sentinel/Log Analytics feature helps?", options: ["Summary rules", "Watchlists", "Playbooks", "Bookmarks"], answer: 0, explain: "Summary rules periodically aggregate large volumes of data into a summarized table, reducing cost and improving query performance." },
  { cat: "sentinel", topic: "s_connectors", q: "When collecting Windows Security events with the Azure Monitor Agent, how do you control whether All, Common, or Minimal events are collected?", options: ["Configure the Data Collection Rule (DCR) event set", "Edit the analytics rule", "Change the commitment tier", "Use a watchlist"], answer: 0, explain: "The DCR for the Windows Security Events connector defines the event set (All/Common/Minimal/custom XPath), controlling volume." },
  { cat: "sentinel", topic: "s_connectors", q: "You need to send custom application logs into a custom table in your Log Analytics workspace for Sentinel. Which method is appropriate?", options: ["The Logs Ingestion API with a Data Collection Rule", "A Fusion rule", "Attack simulation training", "JIT access"], answer: 0, explain: "The Logs Ingestion API (with a DCR and custom table) ingests custom/structured logs into the workspace." },
  { cat: "sentinel", topic: "s_connectors", q: "A team wants to manage Sentinel analytics rules and workbooks as code and deploy them via GitHub or Azure DevOps CI/CD. Which Sentinel feature supports this?", options: ["Repositories (content as code)", "Watchlists", "Livestream", "Fusion"], answer: 0, explain: "Sentinel Repositories connect a GitHub/Azure DevOps repo to deploy content (rules, workbooks) via CI/CD." },

  /* --- Analytics --- */
  { cat: "sentinel", topic: "s_analytics", q: "You want Microsoft Sentinel to detect statistically unusual behavior using tunable machine-learning templates you can customize. Which analytics rule type should you use?", options: ["Anomaly rules", "Scheduled rules only", "Microsoft Security rules", "Threat Intelligence rules"], answer: 0, explain: "Anomaly rules use customizable ML templates to surface unusual behavior; you can tune thresholds and run them in flighting/production." },
  { cat: "sentinel", topic: "s_analytics", q: "In a scheduled analytics rule, you want a SEPARATE alert generated for every matching row (event), not one grouped alert. Which setting controls this?", options: ["Event grouping (trigger an alert for each event vs group all into a single alert)", "Entity mapping", "Commitment tier", "Retention"], answer: 0, explain: "Event grouping determines whether all results form a single alert or each result row generates its own alert." },
  { cat: "sentinel", topic: "s_analytics", q: "You want related alerts produced by a rule over time to be combined into one incident to reduce analyst noise. Which setting should you configure?", options: ["Incident settings / alert grouping on the analytics rule", "A watchlist", "A DCR", "A playbook"], answer: 0, explain: "Alert grouping in the rule's incident settings groups related alerts into a single incident (e.g., by entity, within a time window)." },
  { cat: "sentinel", topic: "s_analytics", q: "When authoring a scheduled analytics rule, why should you map the rule to MITRE ATT&CK tactics and techniques?", options: ["To categorize detections and visualize coverage gaps on the MITRE ATT&CK page", "To reduce ingestion cost", "To grant RBAC", "To create a watchlist"], answer: 0, explain: "Mapping rules to MITRE ATT&CK lets you view detection coverage and identify gaps on the MITRE ATT&CK blade." },
  { cat: "sentinel", topic: "s_analytics", q: "Which is a known limitation of Near-Real-Time (NRT) analytics rules compared to scheduled rules?", options: ["They are limited to a single query and can't do certain joins/lookbacks", "They can only run once per day", "They cannot create incidents", "They require a playbook"], answer: 0, explain: "NRT rules run about every minute but are limited (single query, restricted joins/lookback) versus flexible scheduled rules." },
  { cat: "sentinel", topic: "s_analytics", q: "The fastest way to deploy proven detections in Sentinel is to use prebuilt content rather than writing every rule from scratch. Where do you get these detection templates?", options: ["Analytics rule templates (many from Content hub solutions)", "The Action center", "The investigation graph", "Watchlists"], answer: 0, explain: "Rule templates (installed via Content hub solutions or built-in) let you create effective analytics rules quickly." },
  { cat: "sentinel", topic: "s_analytics", q: "A scheduled rule should look back over the last 24 hours of data and run every hour. Which rule settings define this?", options: ["The query period (lookback) and query frequency (schedule)", "Entity mapping", "Commitment tier", "Event grouping only"], answer: 0, explain: "Query frequency sets how often the rule runs; query period sets the lookback window of data it evaluates." },

  /* --- SOAR --- */
  { cat: "sentinel", topic: "s_soar", q: "A playbook (Logic App) must read from and update Microsoft Sentinel and take actions in Azure using its own identity. What is the recommended way to grant it permissions?", options: ["Assign roles to the playbook's managed identity", "Use a shared user password in the workflow", "Grant Global Administrator to all analysts", "Disable RBAC"], answer: 0, explain: "Grant least-privilege roles to the Logic App's managed identity so the playbook can act securely without stored credentials." },
  { cat: "sentinel", topic: "s_soar", q: "Multiple automation rules apply to the same incident. What determines which runs first?", options: ["The automation rules' configured order", "Alphabetical name only", "Random selection", "The commitment tier"], answer: 0, explain: "Automation rules execute in the order you configure; order matters when several rules match the same incident." },
  { cat: "sentinel", topic: "s_soar", q: "You want a playbook that an analyst can run on demand against a specific IP or account entity for enrichment. Which trigger should the playbook use?", options: ["The Microsoft Sentinel entity trigger", "A recurrence timer", "A blob-created trigger", "An HTTP GET only"], answer: 0, explain: "The entity trigger lets a playbook run against a specific entity (IP, account, host) for on-demand enrichment/response." },
  { cat: "sentinel", topic: "s_soar", q: "Low-value incidents from a specific noisy rule should be closed automatically. What is the simplest way to do this?", options: ["An automation rule that changes the incident status to Closed based on conditions", "Delete the workspace", "Disable all connectors", "A watchlist"], answer: 0, explain: "An automation rule can auto-close (set status/classification) incidents matching conditions, reducing noise without deleting the rule." },
  { cat: "sentinel", topic: "s_soar", q: "You want a playbook to add geo-IP context and a comment to an incident automatically. What category of automation is this?", options: ["Enrichment", "Ingestion", "Vulnerability assessment", "Compliance reporting"], answer: 0, explain: "Enrichment playbooks add context (geo-IP, reputation, comments) to incidents to speed triage." },
  { cat: "sentinel", topic: "s_soar", q: "An analyst needs to run playbooks manually on incidents but should not edit Sentinel content or analytics rules. Which role should they be granted?", options: ["Microsoft Sentinel Playbook Operator", "Microsoft Sentinel Contributor", "Owner", "Reader"], answer: 0, explain: "Playbook Operator lets a user run/attach playbooks without content-editing permissions." },

  /* --- Hunting, workbooks, UEBA --- */
  { cat: "sentinel", topic: "s_hunting", q: "During an incident, you want to run a hunting query continuously and be alerted the moment new matching activity appears. Which feature should you use?", options: ["Livestream", "A workbook", "A watchlist", "A summary rule"], answer: 0, explain: "Livestream runs a hunt continuously and notifies you of new matches in near real time." },
  { cat: "sentinel", topic: "s_hunting", q: "Data has been moved to long-term archive. You need to run a KQL search over that archived data for an investigation. What should you run?", options: ["A search job", "A Fusion rule", "A DCR", "A playbook"], answer: 0, explain: "Search jobs (and restore) let you query archived/long-term data that isn't in interactive retention." },
  { cat: "sentinel", topic: "s_hunting", q: "An analyst wants a consolidated timeline of a user's activities, anomalies, and related alerts to investigate suspicious behavior. Which Sentinel capability provides this?", options: ["The entity behavior (UEBA) entity page", "A data connector", "A commitment tier", "An ASR rule"], answer: 0, explain: "Entity pages (powered by UEBA) show a timeline of an entity's activities, insights, and anomalies for investigation." },
  { cat: "sentinel", topic: "s_hunting", q: "A threat hunter wants to see which MITRE ATT&CK tactics and techniques their hunting queries and analytics rules cover. Where can they view this?", options: ["The MITRE ATT&CK coverage view", "The Action center", "The Tenant Allow/Block List", "Secure Score"], answer: 0, explain: "The MITRE ATT&CK page visualizes detection/hunting coverage across tactics and techniques to reveal gaps." },
  { cat: "sentinel", topic: "s_hunting", q: "You reference an imported list of VIP user accounts inside a KQL analytics query. Which Sentinel feature stores that list, accessible via _GetWatchlist()?", options: ["A watchlist", "A bookmark", "A playbook", "A DCR"], answer: 0, explain: "Watchlists store reference data (e.g., VIPs, allowed IPs) that queries access via the _GetWatchlist() function." },

  /* --- Threat intelligence --- */
  { cat: "sentinel", topic: "s_ti", q: "A threat intelligence platform (TIP) needs to push STIX indicators into Microsoft Sentinel programmatically. Which connector/method should be used?", options: ["Threat Intelligence – Upload Indicators API (platforms) connector", "TAXII pull connector only", "A DCR for Windows events", "A watchlist import"], answer: 0, explain: "The Upload Indicators API (platforms) connector lets a TIP push STIX indicators into Sentinel; TAXII is used to pull from a TAXII server." },
  { cat: "sentinel", topic: "s_ti", q: "After ingesting TI indicators, which analytics rule templates automatically match them against your logs (e.g., malicious IPs in network data)?", options: ["The 'TI map' analytics rule templates", "Fusion", "Anomaly", "Microsoft Security"], answer: 0, explain: "The built-in TI map rule templates correlate ThreatIntelligenceIndicator entries against sources like DNS, network, and sign-in logs." },
  { cat: "sentinel", topic: "s_ti", q: "An analyst wants to add, tag, and set expiration/confidence on individual threat indicators in Sentinel. Where do they do this?", options: ["The Threat Intelligence blade (management interface)", "The Action center", "A workbook only", "The commitment tier settings"], answer: 0, explain: "The Threat Intelligence blade lets analysts view, add, tag, and manage indicators (including validity/confidence)." },
  { cat: "sentinel", topic: "s_ti", q: "Which table stores threat intelligence indicators that TI map analytics rules query?", options: ["ThreatIntelligenceIndicator", "SecurityAlert", "Heartbeat", "AuditLogs"], answer: 0, explain: "Ingested indicators are stored in ThreatIntelligenceIndicator, which TI-map rules join against your logs." },

  /* --- Incident management --- */
  { cat: "sentinel", topic: "s_incidents", q: "A SOC lead wants to standardize the steps every analyst follows when handling a phishing incident, tracked as a checklist on the incident. Which feature should they use?", options: ["Incident tasks", "Watchlists", "Bookmarks", "Summary rules"], answer: 0, explain: "Incident tasks provide a standardized checklist of steps on an incident to guide and track analyst actions." },
  { cat: "sentinel", topic: "s_incidents", q: "During investigation, an analyst clicks an account entity in an incident to see its related activities and alerts across the environment. What are they viewing?", options: ["The entity page", "A workbook", "The Content hub", "A DCR"], answer: 0, explain: "Entity pages provide a consolidated view of an entity's activities, insights, and related alerts for investigation." },
  { cat: "sentinel", topic: "s_incidents", q: "Two analysts are collaborating on a Sentinel incident. Which built-in actions support collaboration and handoff?", options: ["Assigning owners, adding comments, and tagging the incident", "Deleting the workspace", "Changing the commitment tier", "Editing DCRs"], answer: 0, explain: "Incidents support ownership assignment, comments, and tags to coordinate investigation and handoff." },
  { cat: "sentinel", topic: "s_incidents", q: "You want new incidents from a specific analytics rule to be automatically assigned to the Tier-1 queue owner as soon as they're created. What should you use?", options: ["An automation rule triggered on incident creation", "A watchlist", "A summary rule", "A search job"], answer: 0, explain: "An automation rule on incident creation can auto-assign owners, set severity, add tags, or run playbooks." },

  /* --- KQL --- */
  { cat: "sentinel", topic: "s_kql", q: "Which KQL function counts the number of DISTINCT values in a column (e.g., unique IP addresses per user)?", options: ["dcount()", "count()", "sum()", "make_list()"], answer: 0, explain: "dcount() returns an approximate distinct count; count() counts rows regardless of uniqueness." },
  { cat: "sentinel", topic: "s_kql", q: "You want the LATEST record per device based on TimeGenerated, keeping all columns. Which KQL function should you use in summarize?", options: ["arg_max(TimeGenerated, *)", "max(TimeGenerated)", "count()", "make_set(TimeGenerated)"], answer: 0, explain: "arg_max(TimeGenerated, *) returns the row with the maximum timestamp per group, preserving all columns; max() returns only the value." },
  { cat: "sentinel", topic: "s_kql", q: "You want to define a reusable value or subquery at the start of a KQL query. Which statement should you use?", options: ["let", "print", "project", "render"], answer: 0, explain: "The let statement binds a name to a value, expression, or subquery for reuse within the query." },
  { cat: "sentinel", topic: "s_kql", q: "A column contains a dynamic array of values and you need one row per array element. Which KQL operator expands it?", options: ["mv-expand", "summarize", "distinct", "top"], answer: 0, explain: "mv-expand expands a dynamic (multi-value) array into multiple rows, one per element." },
  { cat: "sentinel", topic: "s_kql", q: "You want to aggregate all account names per device into a single array column. Which KQL function should you use?", options: ["make_set() (or make_list())", "count()", "dcount()", "parse()"], answer: 0, explain: "make_set() aggregates values into a de-duplicated array; make_list() keeps duplicates. Both are used with summarize." },
  { cat: "sentinel", topic: "s_kql", q: "For best performance when matching a full term in a large text column, which KQL operator is preferred over 'contains'?", options: ["has", "contains", "startswith", "matches regex"], answer: 0, explain: "'has' matches indexed whole terms and is far more efficient than 'contains' (a slower substring scan) on large data." },
  { cat: "sentinel", topic: "s_kql", q: "You need to extract fields (like a username) out of a free-text log message column. Which KQL operator is designed for this?", options: ["parse", "summarize", "union", "render"], answer: 0, explain: "The parse operator extracts structured fields from a string using a pattern; extend with functions can also help." },
  { cat: "sentinel", topic: "s_kql", q: "Which KQL clause visualizes aggregated results over time as a line chart?", options: ["| render timechart", "| project TimeGenerated", "| take 100", "| distinct TimeGenerated"], answer: 0, explain: "render timechart plots time-series results (often after summarize ... by bin(TimeGenerated, ...)) as a line chart." },

  /* ================= EXTRA ALTERNATE FORMATS ================= */

  { type: "multi", cat: "cloud", topic: "c_plans", q: "Which TWO capabilities does Defender for Servers Plan 2 add beyond Plan 1? (Choose two.)", options: ["File Integrity Monitoring (FIM)", "Just-in-time (JIT) VM access", "Safe Links", "TAXII ingestion"], answers: [0, 1], explain: "Plan 2 adds FIM, JIT VM access, OS-level threat detection, and a data ingestion benefit. Safe Links (MDO) and TAXII (Sentinel TI) are unrelated." },
  { type: "multi", cat: "sentinel", topic: "s_analytics", q: "Which TWO analytics rule types exist in Microsoft Sentinel besides Scheduled and Fusion? (Choose two.)", options: ["Near-real-time (NRT)", "Anomaly", "Playbook", "Watchlist"], answers: [0, 1], explain: "NRT and Anomaly are analytics rule types. Playbooks are automation; watchlists are reference data." },
  { type: "multi", cat: "sentinel", topic: "s_soar", q: "Which TWO Microsoft Sentinel roles are involved in running playbooks? (Choose two.)", options: ["Playbook Operator (run playbooks)", "Automation Contributor (let Sentinel run playbooks)", "Reader (view only)", "Global Administrator"], answers: [0, 1], explain: "Playbook Operator runs playbooks; Automation Contributor grants Sentinel permission to run them. Reader is view-only; Global Admin is broad and not required." },
  { type: "multi", cat: "sentinel", topic: "s_kql", q: "Which TWO KQL functions aggregate values into an array within summarize? (Choose two.)", options: ["make_list()", "make_set()", "where()", "render()"], answers: [0, 1], explain: "make_list() (keeps duplicates) and make_set() (de-duplicated) build arrays. where filters; render visualizes." },
  { type: "multi", cat: "xdr", topic: "x_hunting", q: "Which TWO advanced hunting tables help investigate on-premises identity activity? (Choose two.)", options: ["IdentityLogonEvents", "IdentityDirectoryEvents", "EmailAttachmentInfo", "DeviceFileEvents"], answers: [0, 1], explain: "IdentityLogonEvents and IdentityDirectoryEvents surface identity logon and AD directory activity. The others cover email and device files." },

  { type: "yesno", cat: "xdr", topic: "x_endpoint", q: "You need automated investigations to remediate malware on a device group without waiting for analyst approval. Proposed solution: Set the device group's automation level to 'Full - remediate threats automatically'. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. The 'Full' automation level lets AIR remediate automatically; semi-automated levels require approval." },
  { type: "yesno", cat: "sentinel", topic: "s_workspace", q: "You must reduce ingestion cost for a very high-volume, low-value log while keeping it queryable for a short period. Proposed solution: Ingest it using the Basic logs table plan. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. Basic logs lower ingestion cost for high-volume/low-value data, with limited querying and shorter interactive retention." },
  { type: "yesno", cat: "sentinel", topic: "s_ti", q: "Your threat intelligence platform must PUSH STIX indicators into Microsoft Sentinel programmatically. Proposed solution: Configure the Threat Intelligence – TAXII data connector. Does this meet the goal?", options: ["Yes", "No"], answer: 1, explain: "No. TAXII pulls from a TAXII server. To push from a platform, use the Threat Intelligence Upload Indicators API (platforms) connector." },
  { type: "yesno", cat: "sentinel", topic: "s_soar", q: "You want new incidents from a noisy rule closed automatically without editing the analytics rule. Proposed solution: Create an automation rule that sets the incident status to Closed based on conditions. Does this meet the goal?", options: ["Yes", "No"], answer: 0, explain: "Yes. An automation rule can auto-close matching incidents centrally, leaving the analytics rule intact." },

  { type: "sentence", cat: "sentinel", topic: "s_workspace", segments: ["In Log Analytics, the ", { options: ["Analytics", "Basic"], answer: 1 }, " logs plan is cheapest for high-volume, low-value data, while the ", { options: ["Analytics", "Basic"], answer: 0 }, " logs plan supports full query features and alerting."], explain: "Basic logs = low-cost, limited querying; Analytics logs = full features (alerts, longer interactive retention)." },
  { type: "sentence", cat: "sentinel", topic: "s_kql", segments: ["To keep the latest record per group with all columns, use ", { options: ["arg_max(TimeGenerated, *)", "max(TimeGenerated)"], answer: 0 }, "; to return only the newest value, use ", { options: ["arg_max(TimeGenerated, *)", "max(TimeGenerated)"], answer: 1 }, "."], explain: "arg_max(TimeGenerated, *) returns the whole latest row; max() returns just the maximum value." },
  { type: "sentence", cat: "sentinel", topic: "s_kql", segments: ["For matching a full indexed term in large data, ", { options: ["has", "contains"], answer: 0 }, " is more efficient, while ", { options: ["has", "contains"], answer: 1 }, " does a slower substring scan."], explain: "'has' matches indexed whole terms (fast); 'contains' scans substrings (slower)." },

  /* ---- Hybrid environment scenario (mapped from the course-notes diagram) ---- */
  { cat: "xdr", topic: "x_identity", q: "A hybrid organization runs on-premises Active Directory with two domain controllers using Kerberos and legacy NTLM. They need to detect identity attacks (e.g., Pass-the-Ticket, DCSync) against this on-premises AD. Where must the Microsoft Defender for Identity sensor be deployed?", options: ["On the on-premises domain controllers (and AD FS / AD CS)", "On every user workstation", "In the Azure portal only", "On the perimeter web server"], answer: 0, explain: "Defender for Identity sensors run on the domain controllers (and AD FS/AD CS) to monitor authentication and directory traffic for on-premises identity threats." },
  { cat: "xdr", topic: "x_identity", q: "In the hybrid environment, on-premises Active Directory identities are synchronized to Microsoft Entra ID so users have one identity across on-prem and cloud. Which component performs this synchronization?", options: ["Microsoft Entra Connect (formerly Azure AD Connect)", "Microsoft Defender for Identity", "Microsoft Intune", "Azure Arc"], answer: 0, explain: "Microsoft Entra Connect synchronizes on-premises AD accounts to Entra ID, enabling hybrid identity; Entra ID Protection then covers cloud identity risk." },
  { cat: "cloud", topic: "c_plans", q: "The organization's on-premises Hyper-V servers (file, SQL, Exchange) must receive Microsoft Defender for Cloud workload protection and threat detection. What must you do first to bring these non-Azure servers into Defender for Cloud?", options: ["Onboard them with Azure Arc and the Azure Monitor Agent", "Recreate them as SaaS apps", "Deploy a Defender for Identity sensor on each", "Enable Safe Links"], answer: 0, explain: "Non-Azure/on-premises servers are connected to Defender for Cloud by onboarding them with Azure Arc (with the Azure Monitor Agent), extending Defender for Servers protection to them." },
  { cat: "xdr", topic: "x_endpoint", q: "The environment has roughly 1,000 domain-joined Windows computers that need endpoint detection and response. Which product and onboarding method best fits this domain environment?", options: ["Microsoft Defender for Endpoint, onboarded via Group Policy or Intune", "Microsoft Defender for Office 365, onboarded via transport rules", "Microsoft Defender for Identity, onboarded via sensors", "Microsoft Sentinel, onboarded via DCRs"], answer: 0, explain: "Defender for Endpoint provides EDR for the Windows fleet, and domain-joined devices are commonly onboarded at scale via Group Policy or Intune." },
  { cat: "xdr", topic: "x_office", q: "After the organization moves mailboxes from on-premises Exchange to Exchange Online, which product protects that cloud email and collaboration (Teams, SharePoint Online, OneDrive) against phishing and malicious attachments?", options: ["Microsoft Defender for Office 365", "Microsoft Defender for Identity", "Microsoft Defender for Cloud", "Azure Arc"], answer: 0, explain: "Defender for Office 365 protects Exchange Online and Microsoft 365 collaboration workloads with Safe Links, Safe Attachments, anti-phishing, and ZAP." },
  { cat: "sentinel", topic: "s_connectors", q: "The SOC wants every signal from the hybrid environment — on-premises AD, the Windows endpoints, Microsoft 365, and Azure — centralized for correlation, hunting, and automated response. What should they implement, and how?", options: ["Microsoft Sentinel, ingesting the sources via data connectors", "Defender for Identity, using sensors only", "Azure Arc, using JIT access", "A single ASR rule"], answer: 0, explain: "Microsoft Sentinel (SIEM + SOAR) centralizes signals from Defender XDR, Entra ID, Microsoft 365, and Azure via data connectors for correlation, hunting, and SOAR." },
  ];

  window.AZ_QUESTIONS = (window.AZ_QUESTIONS || []).concat(extra);
})();
