/* =====================================================================
   SC-200 Study Hub — scenario question bank
   Microsoft Security Operations Analyst. Scenario-style, single best
   answer, covering every topic across the three product domains.
   Answers reflect current Microsoft Learn / product documentation.

   Loaded BEFORE js/data.js, which exposes these as AZ.QUESTIONS.
   Each item: { cat, topic, q, options[], answer(index), explain }
   ===================================================================== */
window.AZ_QUESTIONS = [

  /* ===================== DEFENDER XDR ===================== */

  /* --- Defender for Endpoint --- */
  { cat: "xdr", topic: "x_endpoint", q: "During an investigation, an analyst determines a Windows device is actively communicating with a command-and-control server. They must immediately cut the device off from the network while keeping it available for investigation in the Defender portal. Which response action should they take?", options: ["Run an antivirus scan", "Isolate the device", "Restrict app execution", "Collect an investigation package"], answer: 1, explain: "Isolating a device disconnects it from the network (except the Defender service) so it can't spread the attack, while remaining manageable for investigation." },
  { cat: "xdr", topic: "x_endpoint", q: "A security team wants to block Office applications from creating child processes and prevent credential theft from LSASS across their Windows fleet. Which Microsoft Defender for Endpoint capability should they configure?", options: ["Attack Surface Reduction (ASR) rules", "Just-in-time VM access", "Safe Attachments", "Conditional Access"], answer: 0, explain: "ASR rules block risky behaviors such as Office apps spawning child processes and credential theft from LSASS. They can run in audit or block mode." },
  { cat: "xdr", topic: "x_endpoint", q: "An analyst needs to prevent a specific malicious file (identified by its SHA-256 hash) from running on any onboarded device. What should they create in Microsoft Defender for Endpoint?", options: ["A suppression rule", "A custom indicator (IoC) to block the file hash", "An ASR rule", "A device group"], answer: 1, explain: "Custom indicators let you allow or block file hashes, IPs, URLs/domains, and certificates across onboarded devices." },
  { cat: "xdr", topic: "x_endpoint", q: "A company wants to onboard hundreds of Windows devices to Microsoft Defender for Endpoint and already manages them with Microsoft Intune. What is the most efficient onboarding method?", options: ["Run the local onboarding script manually on each device", "Use a Microsoft Intune configuration/endpoint security policy to onboard the devices", "Email users the onboarding package", "Use Azure Arc"], answer: 1, explain: "For Intune-managed devices, onboarding via an Intune policy scales automatically without touching each device." },
  { cat: "xdr", topic: "x_endpoint", q: "An analyst needs to run live forensic commands (e.g., pull a file, run a script) directly on a compromised device from the Defender portal. Which feature should they use?", options: ["Live response", "Advanced hunting", "Automated investigation", "Threat analytics"], answer: 0, explain: "Live response gives analysts a remote command shell on the device to investigate and remediate in real time (collect files, run scripts, etc.)." },
  { cat: "xdr", topic: "x_endpoint", q: "A SOC wants to prioritize patching based on which vulnerabilities are most likely to be exploited on their actual devices. Which Microsoft Defender for Endpoint capability provides this risk-based view?", options: ["Defender Vulnerability Management", "Attack simulation training", "Safe Links", "Cloud Discovery"], answer: 0, explain: "Defender Vulnerability Management discovers and prioritizes device weaknesses with risk-based context and remediation guidance." },
  { cat: "xdr", topic: "x_endpoint", q: "An analyst suspects malware on a device but wants Defender for Endpoint to gather detailed forensic artifacts (running processes, network connections, autoruns) for offline analysis. Which action should they choose?", options: ["Isolate device", "Collect investigation package", "Restrict app execution", "Run antivirus scan"], answer: 1, explain: "Collect investigation package gathers forensic data (processes, network, scheduled tasks, etc.) from the device for analysis." },
  { cat: "xdr", topic: "x_endpoint", q: "A security administrator wants to scope which analysts can see and take action on which devices, based on device groups. Which Defender for Endpoint feature enables this?", options: ["Role-based access control (RBAC) with device groups", "Conditional Access", "Automation rules", "Watchlists"], answer: 0, explain: "MDE RBAC combined with device groups restricts which users can view and act on which devices, enforcing least privilege." },

  /* --- Defender for Office 365 --- */
  { cat: "xdr", topic: "x_office", q: "A company wants email attachments to be opened in an isolated sandbox and checked for malicious behavior before being delivered to users. Which Microsoft Defender for Office 365 feature provides this?", options: ["Safe Links", "Safe Attachments", "Anti-spam policy", "Zero-hour Auto Purge"], answer: 1, explain: "Safe Attachments detonates attachments in a virtual sandbox to detect malicious behavior before delivery." },
  { cat: "xdr", topic: "x_office", q: "Users clicked a link that was safe when the email arrived but later became malicious. The security team wants URLs re-checked at the moment of click. Which feature addresses this?", options: ["Safe Attachments", "Safe Links (time-of-click protection)", "Tenant Allow/Block List", "Quarantine policy"], answer: 1, explain: "Safe Links rewrites URLs and scans them at time of click, protecting against links that are weaponized after delivery." },
  { cat: "xdr", topic: "x_office", q: "After new threat intelligence, malicious phishing emails already delivered to users' inboxes need to be removed automatically. Which Defender for Office 365 capability does this?", options: ["Zero-hour Auto Purge (ZAP)", "Safe Attachments", "Attack simulation training", "Configuration analyzer"], answer: 0, explain: "ZAP retroactively detects and removes malicious or spam messages already delivered to mailboxes." },
  { cat: "xdr", topic: "x_office", q: "A security team wants to apply Microsoft's recommended baseline email protection quickly without manually configuring each policy. What should they use?", options: ["Preset security policies (Standard/Strict)", "A transport rule", "A custom anti-malware policy only", "Tenant Allow/Block List"], answer: 0, explain: "Preset security policies apply Microsoft's recommended Standard or Strict baseline settings for anti-phishing, Safe Links, and Safe Attachments." },
  { cat: "xdr", topic: "x_office", q: "An analyst wants to hunt through email data to see all messages that delivered a specific malicious URL and take remediation actions like soft-deleting them. Which tool should they use?", options: ["Threat Explorer (Explorer)", "Cloud Discovery", "Secure Score", "Attack Surface Reduction"], answer: 0, explain: "Threat Explorer (Explorer / real-time detections) lets analysts investigate email threats and take actions such as soft-delete on matching messages." },
  { cat: "xdr", topic: "x_office", q: "A legitimate sender is being incorrectly blocked by Defender for Office 365. Which is the correct place to create an allow entry for that sender or domain?", options: ["Tenant Allow/Block List", "An ASR rule", "A custom detection rule", "A watchlist"], answer: 0, explain: "The Tenant Allow/Block List is where admins manage allow/block entries for senders, domains, URLs, files, and spoofed identities." },

  /* --- Defender for Identity --- */
  { cat: "xdr", topic: "x_identity", q: "An organization wants to detect on-premises Active Directory attacks such as Pass-the-Ticket and DCSync. Which Microsoft solution should they deploy?", options: ["Microsoft Defender for Identity", "Microsoft Defender for Cloud Apps", "Microsoft Entra ID Protection", "Microsoft Defender for Endpoint"], answer: 0, explain: "Microsoft Defender for Identity monitors on-premises AD to detect identity threats like Pass-the-Ticket, Golden Ticket, and DCSync." },
  { cat: "xdr", topic: "x_identity", q: "Where are Microsoft Defender for Identity sensors installed?", options: ["On end-user laptops", "On domain controllers, AD FS, and AD CS servers", "In the Azure portal only", "On the mail server"], answer: 1, explain: "MDI sensors run directly on domain controllers (and AD FS / AD CS servers) to monitor authentication and directory traffic locally." },
  { cat: "xdr", topic: "x_identity", q: "Defender for Identity flags a large number of LDAP queries enumerating accounts and groups from a single workstation. Which attack phase does this represent?", options: ["Reconnaissance", "Exfiltration", "Persistence", "Impact"], answer: 0, explain: "Enumerating accounts, groups, and structure of AD is reconnaissance — an early phase used to plan lateral movement." },
  { cat: "xdr", topic: "x_identity", q: "Which identity-protection capability detects RISKY SIGN-INS and RISKY USERS for cloud identities and can trigger risk-based Conditional Access?", options: ["Microsoft Defender for Identity", "Microsoft Entra ID Protection", "Microsoft Defender for Endpoint", "File Integrity Monitoring"], answer: 1, explain: "Microsoft Entra ID Protection detects risky sign-ins/users for cloud identities and can drive risk-based Conditional Access policies." },
  { cat: "xdr", topic: "x_identity", q: "A user's identity in Defender for Identity is repeatedly used to authenticate to many systems in a short time from an unusual host, suggesting stolen credentials moving through the network. Which threat category is this?", options: ["Lateral movement", "Data loss prevention", "Shadow IT", "Vulnerability", ], answer: 0, explain: "Using compromised credentials to move between systems is lateral movement, which MDI detects via techniques like Pass-the-Hash/Ticket." },

  /* --- Defender for Cloud Apps --- */
  { cat: "xdr", topic: "x_mda", q: "A company wants to discover unsanctioned SaaS applications ('Shadow IT') being used on their network by analyzing firewall and proxy logs. Which Microsoft Defender for Cloud Apps capability provides this?", options: ["Cloud Discovery", "Conditional Access App Control", "Safe Links", "Just-in-time access"], answer: 0, explain: "Cloud Discovery analyzes traffic logs to reveal which cloud apps are in use, their risk, and usage — surfacing Shadow IT." },
  { cat: "xdr", topic: "x_mda", q: "A security team must block downloads of sensitive files during risky web sessions to a sanctioned SaaS app in real time. Which Defender for Cloud Apps capability enforces this?", options: ["Conditional Access App Control (session policies)", "Cloud Discovery", "Attack Surface Reduction", "Automated investigation"], answer: 0, explain: "Conditional Access App Control (a reverse proxy integrated with Entra Conditional Access) enforces real-time session policies such as blocking downloads." },
  { cat: "xdr", topic: "x_mda", q: "What type of security solution is Microsoft Defender for Cloud Apps?", options: ["A Cloud Access Security Broker (CASB)", "An endpoint EDR", "A SIEM", "A vulnerability scanner"], answer: 0, explain: "Defender for Cloud Apps is a CASB, providing visibility and control over cloud app usage and data." },
  { cat: "xdr", topic: "x_mda", q: "An analyst wants to connect Microsoft Defender for Cloud Apps to a sanctioned SaaS app via API to get deep visibility into activities and files (not just log-based discovery). What should they configure?", options: ["An app connector", "A data connector in Sentinel", "A watchlist", "A DCR"], answer: 0, explain: "App connectors use the app's APIs to give MDA rich visibility and governance over activities, files, and accounts in the connected app." },
  { cat: "xdr", topic: "x_mda", q: "Defender for Cloud Apps raises an alert for 'impossible travel' where a user signs in from two distant locations within minutes. What type of policy detected this?", options: ["An anomaly detection policy", "A Safe Attachments policy", "A JIT policy", "A FIM rule"], answer: 0, explain: "Anomaly detection policies in Defender for Cloud Apps use behavioral analytics to flag activities like impossible travel and unusual downloads." },

  /* --- XDR Incidents & Response --- */
  { cat: "xdr", topic: "x_incidents", q: "In the Microsoft Defender portal, several alerts from Defender for Endpoint and Defender for Office 365 have been grouped together telling the story of one attack. What is this grouping called?", options: ["An incident", "A workbook", "A watchlist", "A playbook"], answer: 0, explain: "Defender XDR automatically correlates related alerts and evidence across products into a single incident." },
  { cat: "xdr", topic: "x_incidents", q: "An analyst wants Defender XDR to automatically investigate alerts and remediate malicious artifacts (e.g., quarantine files) with little manual effort. Which capability should be enabled?", options: ["Automated investigation and response (AIR)", "Advanced hunting", "Secure Score", "Content hub"], answer: 0, explain: "Automated investigation and response (AIR) investigates alerts, reaches verdicts, and can automatically take or recommend remediation actions." },
  { cat: "xdr", topic: "x_incidents", q: "When triaging an incident, an analyst confirms it is a false positive. What should they set the incident classification to?", options: ["Classify it as a false positive (and set determination)", "Delete the underlying logs", "Isolate all devices", "Raise the severity to High"], answer: 0, explain: "Classifying incidents (true/false positive with a determination) improves accuracy of detections and Automated investigation over time." },
  { cat: "xdr", topic: "x_incidents", q: "A manager wants each analyst to own the incidents they are working. Which incident management action supports this?", options: ["Assign the incident to a user", "Create a data connector", "Add an ASR rule", "Enable a Defender plan"], answer: 0, explain: "Assigning incidents to owners and updating status/tags keeps investigations organized and accountable." },
  { cat: "xdr", topic: "x_incidents", q: "An organization wants Microsoft Defender XDR incidents (and alerts) to appear and be managed in Microsoft Sentinel alongside other sources. What should they configure?", options: ["The Microsoft Defender XDR data connector in Microsoft Sentinel", "A custom detection rule", "A JIT policy", "An anti-phishing policy"], answer: 0, explain: "The Microsoft Defender XDR connector streams XDR incidents/alerts (with bi-directional sync) into Microsoft Sentinel." },
  { cat: "xdr", topic: "x_incidents", q: "Which portal is the single pane of glass for viewing and managing Microsoft Defender XDR incidents?", options: ["The Microsoft Defender portal (security.microsoft.com)", "The Azure portal", "The Microsoft Purview portal", "The Microsoft Intune admin center"], answer: 0, explain: "The Microsoft Defender portal at security.microsoft.com is the unified console for Defender XDR incidents and investigations." },

  /* --- Advanced Hunting --- */
  { cat: "xdr", topic: "x_hunting", q: "An analyst wants to proactively search raw endpoint and email telemetry across the tenant using KQL to find suspicious PowerShell activity. Which Defender XDR feature should they use?", options: ["Advanced hunting", "Secure Score", "Attack simulation training", "Threat analytics"], answer: 0, explain: "Advanced hunting is the KQL-based query tool over the unified Defender XDR schema for proactive threat hunting." },
  { cat: "xdr", topic: "x_hunting", q: "An analyst has written an advanced hunting query that reliably identifies a specific attack technique. They want it to generate alerts automatically on a schedule. What should they create?", options: ["A custom detection rule from the query", "A workbook", "A watchlist", "A playbook"], answer: 0, explain: "Saving an advanced hunting query as a custom detection rule makes it run on a schedule, generate alerts, and optionally take response actions." },
  { cat: "xdr", topic: "x_hunting", q: "In Defender XDR advanced hunting, which table would you primarily query to find process creation events on devices?", options: ["DeviceProcessEvents", "EmailEvents", "CloudAppEvents", "IdentityInfo"], answer: 0, explain: "DeviceProcessEvents contains process creation telemetry from endpoints; EmailEvents is for mail, CloudAppEvents for app activity, IdentityInfo for identities." },
  { cat: "xdr", topic: "x_hunting", q: "An analyst needs to correlate an alert with the specific entities (files, IPs, accounts) that triggered it in advanced hunting. Which two tables are most useful together?", options: ["AlertInfo and AlertEvidence", "DeviceLogonEvents and Heartbeat", "SigninLogs and AuditLogs", "EmailUrlInfo and UrlClickEvents"], answer: 0, explain: "AlertInfo (alert details) joined with AlertEvidence (entities/evidence per alert) links alerts to the files, IPs, and accounts involved." },
  { cat: "xdr", topic: "x_hunting", q: "Which query language is used for advanced hunting in Microsoft Defender XDR?", options: ["KQL (Kusto Query Language)", "SQL", "PowerShell", "SPL"], answer: 0, explain: "Advanced hunting (like Sentinel and Log Analytics) uses KQL, the Kusto Query Language." },
  { cat: "xdr", topic: "x_hunting", q: "An analyst wants email-related hunting results in advanced hunting to show which delivered messages contained a malicious URL that users clicked. Which tables would they combine?", options: ["EmailEvents / EmailUrlInfo with UrlClickEvents", "DeviceFileEvents with DeviceRegistryEvents", "IdentityLogonEvents with DeviceNetworkEvents", "CloudAppEvents with AlertInfo"], answer: 0, explain: "EmailEvents/EmailUrlInfo describe delivered mail and URLs, and UrlClickEvents records Safe Links click activity — combined they show delivery-to-click." },

  /* ===================== DEFENDER FOR CLOUD ===================== */

  /* --- CSPM & Secure Score --- */
  { cat: "cloud", topic: "c_cspm", q: "A security team wants a single percentage that reflects how well their Azure environment follows security best practices, improving as they fix recommendations. What should they monitor in Microsoft Defender for Cloud?", options: ["Secure Score", "Commitment tier", "Log Analytics usage", "Threat intelligence"], answer: 0, explain: "Secure Score summarizes posture based on remediated recommendations; addressing recommendations raises the score." },
  { cat: "cloud", topic: "c_cspm", q: "Which capability of Microsoft Defender for Cloud is FREE and continuously assesses resource configuration against best practices to produce recommendations?", options: ["Foundational CSPM", "Defender for Servers", "Defender for SQL", "Just-in-time VM access"], answer: 0, explain: "Foundational Cloud Security Posture Management (CSPM) — recommendations and Secure Score — is available for free; workload protection (Defender plans) is paid." },
  { cat: "cloud", topic: "c_cspm", q: "Which built-in initiative drives the default recommendations and Secure Score in Microsoft Defender for Cloud?", options: ["Microsoft Cloud Security Benchmark (MCSB)", "PCI-DSS", "MITRE ATT&CK", "NIST SP 800-53"], answer: 0, explain: "The Microsoft Cloud Security Benchmark is the default policy initiative that generates recommendations and feeds Secure Score." },
  { cat: "cloud", topic: "c_cspm", q: "A company runs workloads in AWS and Azure and wants unified posture recommendations across both from Microsoft Defender for Cloud. What must they do?", options: ["Connect the AWS account using the multicloud connector", "Install Sentinel on AWS", "Deploy MDE to every AWS EC2 manually only", "Nothing — AWS is covered automatically"], answer: 0, explain: "Defender for Cloud provides multicloud CSPM by connecting AWS (and GCP) accounts via its native cloud connector." },
  { cat: "cloud", topic: "c_cspm", q: "An analyst wants to see all cloud resources and their security state in one inventory, filtered by recommendations and Defender plan coverage. Which Defender for Cloud feature helps?", options: ["Asset inventory", "Live response", "Attack simulation", "Watchlists"], answer: 0, explain: "The asset inventory lists resources with their security posture, active recommendations, and coverage, and supports filtering/queries." },
  { cat: "cloud", topic: "c_cspm", q: "A recommendation in Defender for Cloud offers a one-click fix to remediate a misconfiguration on multiple resources. What is this called?", options: ["Quick Fix remediation", "A playbook", "An analytics rule", "A watchlist"], answer: 0, explain: "Many recommendations provide a 'Quick Fix' to remediate the issue across affected resources with minimal effort." },

  /* --- Workload Protection Plans --- */
  { cat: "cloud", topic: "c_plans", q: "A company wants threat detection for their Azure virtual machines, including integration with Defender for Endpoint and just-in-time port access. Which Defender for Cloud plan should they enable?", options: ["Defender for Servers", "Defender for Storage", "Defender for Key Vault", "Defender for DNS"], answer: 0, explain: "Defender for Servers protects VMs/servers, integrates Defender for Endpoint, and provides JIT VM access, FIM, and vulnerability assessment." },
  { cat: "cloud", topic: "c_plans", q: "To reduce brute-force attacks, a team wants RDP/SSH management ports on VMs kept closed and opened only on approved request for a limited time. Which feature provides this?", options: ["Just-in-time (JIT) VM access", "File Integrity Monitoring", "Adaptive network hardening off", "Secure Score"], answer: 0, explain: "Just-in-time VM access keeps management ports closed and grants time-limited access only when requested and approved." },
  { cat: "cloud", topic: "c_plans", q: "A company stores sensitive data in Azure Storage accounts and wants alerts on malware uploads and suspicious access. Which Defender plan should they enable?", options: ["Defender for Storage", "Defender for Servers", "Defender for Resource Manager", "Defender for APIs"], answer: 0, explain: "Defender for Storage detects malicious activity on storage accounts, including malware scanning of uploaded blobs and anomalous access." },
  { cat: "cloud", topic: "c_plans", q: "A team needs to monitor critical OS files and registry keys on servers for unauthorized changes. Which Defender for Cloud capability provides this?", options: ["File Integrity Monitoring (FIM)", "Cloud Discovery", "Safe Links", "Fusion"], answer: 0, explain: "File Integrity Monitoring (part of Defender for Servers) tracks changes to critical files, registry keys, and OS files that may indicate compromise." },
  { cat: "cloud", topic: "c_plans", q: "An organization wants to detect suspicious control-plane operations (like risky role assignments or resource deployments) in their Azure subscription. Which Defender plan is designed for this?", options: ["Defender for Resource Manager", "Defender for Endpoint", "Defender for Office 365", "Defender for Identity"], answer: 0, explain: "Defender for Resource Manager monitors Azure Resource Manager control-plane operations for suspicious or malicious activity." },
  { cat: "cloud", topic: "c_plans", q: "A company runs containers in Azure Kubernetes Service and wants runtime threat detection and hardening recommendations. Which plan should they enable?", options: ["Defender for Containers", "Defender for SQL", "Defender for DNS", "Defender for Key Vault"], answer: 0, explain: "Defender for Containers provides posture hardening, vulnerability assessment, and runtime threat protection for Kubernetes/containers." },
  { cat: "cloud", topic: "c_plans", q: "When a Defender for Cloud security alert fires, a team wants to automatically open a ticket and notify the SOC. What should they configure?", options: ["Workflow automation with a Logic App", "A Sentinel workbook", "A watchlist", "An ASR rule"], answer: 0, explain: "Workflow automation triggers a Logic App on alerts/recommendations to automate responses like ticketing and notifications." },

  /* --- Regulatory Compliance --- */
  { cat: "cloud", topic: "c_compliance", q: "An auditor needs to see how the Azure environment measures against PCI-DSS and ISO 27001 controls. Which Microsoft Defender for Cloud feature should the analyst use?", options: ["Regulatory compliance dashboard", "Secure Score only", "Advanced hunting", "Cloud Discovery"], answer: 0, explain: "The Regulatory compliance dashboard maps your environment against standards like PCI-DSS, ISO 27001, NIST, and CIS." },
  { cat: "cloud", topic: "c_compliance", q: "A company wants to add a specific industry standard (e.g., NIST SP 800-53) to their compliance view in Defender for Cloud. What is generally required?", options: ["At least one paid Defender plan enabled on the subscription", "Only the free tier", "Microsoft Sentinel", "Defender for Identity sensors"], answer: 0, explain: "Adding regulatory standards beyond the default benchmark to the compliance dashboard requires an enabled (paid) Defender plan." },
  { cat: "cloud", topic: "c_compliance", q: "The compliance dashboard shows a failing control. What is the recommended next step to improve compliance?", options: ["Remediate the underlying security recommendations mapped to that control", "Delete the standard", "Disable Defender for Cloud", "Ignore it — compliance is automatic"], answer: 0, explain: "Compliance controls map to security recommendations; remediating those recommendations improves the control's compliance status." },

  /* ===================== MICROSOFT SENTINEL ===================== */

  /* --- Workspace & Roles --- */
  { cat: "sentinel", topic: "s_workspace", q: "What is Microsoft Sentinel built on top of?", options: ["A Log Analytics workspace", "An Azure Storage account", "A SQL database", "A Cosmos DB account"], answer: 0, explain: "Microsoft Sentinel is enabled on a Log Analytics workspace and uses KQL over the data stored there." },
  { cat: "sentinel", topic: "s_workspace", q: "An analyst must be able to view Sentinel data and manage (triage, close) incidents, but not create analytics rules or connectors. Which built-in role fits best?", options: ["Microsoft Sentinel Responder", "Microsoft Sentinel Reader", "Microsoft Sentinel Contributor", "Owner"], answer: 0, explain: "Microsoft Sentinel Responder can view data and manage incidents; Reader is view-only; Contributor can create content." },
  { cat: "sentinel", topic: "s_workspace", q: "A team wants Sentinel to be able to run a specific playbook (Logic App) as part of automation, following least privilege. Which role should be granted to Sentinel on the playbook's resource group?", options: ["Microsoft Sentinel Automation Contributor", "Owner", "Microsoft Sentinel Reader", "Global Administrator"], answer: 0, explain: "The Microsoft Sentinel Automation Contributor role lets Sentinel run playbooks; granting it (rather than broad roles) follows least privilege." },
  { cat: "sentinel", topic: "s_workspace", q: "A user should be able to run playbooks manually on incidents but not modify Sentinel content. Which role is appropriate?", options: ["Microsoft Sentinel Playbook Operator", "Microsoft Sentinel Contributor", "Reader", "Security Administrator"], answer: 0, explain: "The Playbook Operator role allows running/attaching playbooks without granting broader content-editing permissions." },

  /* --- Data Connectors & Ingestion --- */
  { cat: "sentinel", topic: "s_connectors", q: "A SOC wants to ingest sign-in and audit logs from Microsoft Entra ID into Microsoft Sentinel. What is the correct approach?", options: ["Enable the Microsoft Entra ID data connector in Sentinel", "Write a custom KQL rule", "Deploy a Defender for Identity sensor", "Create a watchlist"], answer: 0, explain: "Data connectors ingest data sources; the Microsoft Entra ID connector brings sign-in and audit logs into Sentinel." },
  { cat: "sentinel", topic: "s_connectors", q: "A company needs to collect Syslog and CEF logs from on-premises network appliances into Microsoft Sentinel. Which component collects and forwards these logs?", options: ["A Linux log-forwarder running the Azure Monitor Agent (AMA)", "Defender for Endpoint", "A playbook", "A watchlist"], answer: 0, explain: "CEF/Syslog are collected via a Linux forwarder running the Azure Monitor Agent, which sends the data to the workspace." },
  { cat: "sentinel", topic: "s_connectors", q: "Which statement about ingesting Microsoft Defender XDR data into Sentinel is correct?", options: ["Many Microsoft first-party connectors ingest data at no additional ingestion cost", "All Microsoft data costs the same as third-party data", "You must use CEF for Microsoft data", "Microsoft data cannot be ingested into Sentinel"], answer: 0, explain: "Many Microsoft first-party sources (e.g., Defender XDR alerts/incidents) can be ingested into Sentinel without extra ingestion charges." },
  { cat: "sentinel", topic: "s_connectors", q: "A team wants a packaged solution that installs a product's data connector, analytics rules, workbooks, and playbooks together in Sentinel. Where should they look?", options: ["The Content hub", "The investigation graph", "The Tenant Allow/Block List", "The asset inventory"], answer: 0, explain: "The Content hub provides packaged solutions (connectors + analytics + workbooks + playbooks) for many products." },
  { cat: "sentinel", topic: "s_connectors", q: "An analyst needs to control which specific events from a Windows Security log are collected to reduce ingestion cost. Which mechanism defines what data is collected by the Azure Monitor Agent?", options: ["A Data Collection Rule (DCR)", "An analytics rule", "A watchlist", "A playbook"], answer: 0, explain: "Data Collection Rules (DCRs) define what the Azure Monitor Agent collects and where it is sent, allowing filtering to control volume/cost." },

  /* --- Analytics Rules --- */
  { cat: "sentinel", topic: "s_analytics", q: "A SOC wants Sentinel to detect a specific pattern by running a KQL query every hour and creating an incident when it matches. Which analytics rule type should they create?", options: ["Scheduled analytics rule", "Fusion rule", "Microsoft Security rule", "Anomaly rule"], answer: 0, explain: "A Scheduled analytics rule runs a KQL query on a defined interval and generates alerts/incidents on matches." },
  { cat: "sentinel", topic: "s_analytics", q: "A team wants Sentinel to automatically detect multistage attacks by correlating low-fidelity signals across products using machine learning. Which rule type provides this?", options: ["Fusion", "Scheduled", "Near-real-time (NRT)", "Threat Intelligence"], answer: 0, explain: "Fusion is a built-in ML analytics rule that correlates signals across products to surface high-fidelity multistage attack incidents." },
  { cat: "sentinel", topic: "s_analytics", q: "A detection must fire as quickly as possible — close to every minute — for a critical scenario. Which analytics rule type is designed for the lowest latency?", options: ["Near-real-time (NRT) rule", "Scheduled rule with a 24-hour period", "Fusion", "Anomaly"], answer: 0, explain: "Near-real-time (NRT) rules run about once per minute for the fastest detection (with some query limitations)." },
  { cat: "sentinel", topic: "s_analytics", q: "An organization wants Microsoft Defender for Cloud alerts to automatically become incidents in Sentinel. Which analytics rule type creates incidents from Microsoft security product alerts?", options: ["Microsoft Security analytics rule", "Scheduled rule", "Anomaly rule", "Threat Intelligence rule"], answer: 0, explain: "Microsoft Security analytics rules automatically create Sentinel incidents from alerts generated by Microsoft security products." },
  { cat: "sentinel", topic: "s_analytics", q: "When creating a scheduled analytics rule, an analyst maps the query's account and IP columns to identities so they can be investigated. What is this mapping called?", options: ["Entity mapping", "Data Collection Rule", "Commitment tier", "Suppression"], answer: 0, explain: "Entity mapping associates query result columns with entities (accounts, hosts, IPs), enabling investigation and correlation." },
  { cat: "sentinel", topic: "s_analytics", q: "An analytics rule is generating too many separate incidents for the same activity. Which rule setting groups related alerts into a single incident?", options: ["Alert grouping (event/incident grouping settings)", "Commitment tier", "Retention", "UEBA"], answer: 0, explain: "Alert grouping settings in the analytics rule can group related alerts into a single incident to reduce noise." },
  { cat: "sentinel", topic: "s_analytics", q: "A tuned analytics rule keeps alerting on a known-benign service account. Which mechanism suppresses those specific matches?", options: ["A suppression / exclusion in the rule logic (e.g., filter the account)", "Deleting the workspace", "Disabling all connectors", "Raising the commitment tier"], answer: 0, explain: "You reduce false positives by refining the KQL (excluding known-benign entities) or using rule tuning/automation to suppress them." },
  { cat: "sentinel", topic: "s_analytics", q: "Which analytics rule type matches ingested logs against threat intelligence indicators (like malicious IPs/domains) to generate alerts?", options: ["Threat Intelligence analytics rule", "Fusion", "NRT", "Anomaly"], answer: 0, explain: "Threat Intelligence analytics rules (e.g., 'TI map' templates) match your logs against TI indicators to raise alerts." },

  /* --- Automation (SOAR) --- */
  { cat: "sentinel", topic: "s_soar", q: "A SOC wants to automatically run a workflow that blocks a user and posts to Teams whenever a high-severity incident is created. What Sentinel component defines that workflow?", options: ["A playbook (Azure Logic App)", "A workbook", "A watchlist", "An analytics rule"], answer: 0, explain: "Playbooks are Logic Apps that automate response actions (block user, notify, isolate device) and can be triggered by incidents/alerts." },
  { cat: "sentinel", topic: "s_soar", q: "A team wants to centrally, automatically assign incidents to an owner and run a playbook whenever incidents from a specific rule appear — without editing each analytics rule. What should they create?", options: ["An automation rule", "A workbook", "A DCR", "A watchlist"], answer: 0, explain: "Automation rules centrally orchestrate incident handling (assign owners, change status, run playbooks, add tags) based on conditions." },
  { cat: "sentinel", topic: "s_soar", q: "Which Azure service are Microsoft Sentinel playbooks built on?", options: ["Azure Logic Apps", "Azure Functions only", "Azure Automation runbooks", "Azure DevOps"], answer: 0, explain: "Sentinel playbooks are Azure Logic Apps, using connectors and triggers to orchestrate automated responses." },
  { cat: "sentinel", topic: "s_soar", q: "An analyst wants a playbook to receive full incident context (entities, alerts) so it can act on them. Which trigger should the playbook use?", options: ["The Microsoft Sentinel incident trigger", "An HTTP request trigger only", "A recurrence timer", "A blob-created trigger"], answer: 0, explain: "The incident trigger passes the incident (with entities and alerts) to the playbook; it's the standard trigger for incident automation." },
  { cat: "sentinel", topic: "s_soar", q: "A playbook needs permission to run automatically from an automation rule. Besides creating the playbook, what must be granted?", options: ["Sentinel must have the Automation Contributor role (permission to run the playbook)", "The user must be Global Admin", "Nothing — it runs automatically", "The workspace must be deleted and recreated"], answer: 0, explain: "For automation rules to run a playbook, the Microsoft Sentinel Automation Contributor permission must be granted on the playbook's resource group." },
  { cat: "sentinel", topic: "s_soar", q: "What do the letters SOAR stand for, describing Sentinel's automation capabilities?", options: ["Security Orchestration, Automation, and Response", "Secure Operations And Reporting", "System Of Automated Rules", "Security Optimization And Remediation"], answer: 0, explain: "SOAR = Security Orchestration, Automation, and Response — automating and coordinating incident response." },

  /* --- Hunting, Workbooks & UEBA --- */
  { cat: "sentinel", topic: "s_hunting", q: "A threat hunter wants to proactively search for threats that have NOT triggered any alerts, using prebuilt KQL queries mapped to MITRE ATT&CK. Which Sentinel feature should they use?", options: ["Hunting queries", "Analytics rules", "Playbooks", "Data connectors"], answer: 0, explain: "The Hunting experience provides KQL hunting queries (mapped to MITRE ATT&CK) for proactively finding undetected threats." },
  { cat: "sentinel", topic: "s_hunting", q: "During hunting, an analyst finds a suspicious result worth keeping for a later investigation and possibly attaching to an incident. What should they create?", options: ["A bookmark", "A workbook", "A watchlist", "An automation rule"], answer: 0, explain: "Bookmarks save interesting hunting results so they can be investigated later and added to incidents." },
  { cat: "sentinel", topic: "s_hunting", q: "A manager wants an interactive visual dashboard showing incident trends and data ingestion over time in Sentinel. Which feature provides visualization?", options: ["Workbooks", "Playbooks", "Watchlists", "Analytics rules"], answer: 0, explain: "Workbooks provide interactive visual dashboards for monitoring and reporting in Microsoft Sentinel." },
  { cat: "sentinel", topic: "s_hunting", q: "A team wants Sentinel to build behavioral baselines and flag anomalous user/entity activity (e.g., first-time actions, unusual volumes). Which capability should they enable?", options: ["UEBA (User and Entity Behavior Analytics)", "JIT VM access", "Safe Attachments", "Content hub"], answer: 0, explain: "UEBA builds baselines and detects anomalies, enriching entities and populating tables like BehaviorAnalytics." },
  { cat: "sentinel", topic: "s_hunting", q: "An advanced analyst wants to run code-driven investigations using Python and MSTICPy against Sentinel data. Which feature supports this?", options: ["Notebooks (Jupyter)", "Workbooks", "Watchlists", "Playbooks"], answer: 0, explain: "Sentinel notebooks (Jupyter) enable advanced, code-driven hunting and investigation with libraries like MSTICPy." },

  /* --- Threat Intelligence --- */
  { cat: "sentinel", topic: "s_ti", q: "A company subscribes to a TAXII threat-intelligence feed and wants those indicators in Microsoft Sentinel. What should they configure?", options: ["The Threat Intelligence – TAXII data connector", "A workbook", "A DCR", "An ASR rule"], answer: 0, explain: "The Threat Intelligence – TAXII connector ingests STIX/TAXII indicator feeds into Sentinel's ThreatIntelligenceIndicator table." },
  { cat: "sentinel", topic: "s_ti", q: "Into which table are threat intelligence indicators stored in Microsoft Sentinel so analytics rules can match logs against them?", options: ["ThreatIntelligenceIndicator", "SecurityIncident", "Heartbeat", "SigninLogs"], answer: 0, explain: "TI indicators live in the ThreatIntelligenceIndicator table, which TI-map analytics rules join against your logs." },
  { cat: "sentinel", topic: "s_ti", q: "A SOC wants to upload their own custom indicators of compromise into Sentinel programmatically. Which connector/method is appropriate?", options: ["The Threat Intelligence Upload Indicators API (platforms) connector", "A Logic App recurrence trigger", "A watchlist of devices", "Defender for Identity sensor"], answer: 0, explain: "The Threat Intelligence Platforms / Upload Indicators API connector lets you push custom indicators into Sentinel." },
  { cat: "sentinel", topic: "s_ti", q: "How are ingested threat-intelligence indicators most commonly USED to generate detections in Sentinel?", options: ["Analytics rules match logs against the indicators to raise alerts", "They automatically isolate devices", "They replace the need for data connectors", "They only appear in workbooks"], answer: 0, explain: "TI indicators are consumed by (TI-map) analytics rules that match them against ingested logs to generate alerts/incidents." },

  /* --- Incident Management --- */
  { cat: "sentinel", topic: "s_incidents", q: "In Microsoft Sentinel, what is created when an analytics rule's alerts meet its incident-creation settings?", options: ["An incident", "A workbook", "A DCR", "A commitment tier"], answer: 0, explain: "Analytics rules can create incidents (groupings of alerts) that analysts triage, investigate, and resolve." },
  { cat: "sentinel", topic: "s_incidents", q: "An analyst wants to visually explore an incident's related entities and how they connect (accounts, hosts, IPs). Which Sentinel tool should they use?", options: ["The investigation graph", "A workbook", "A watchlist", "Cloud Discovery"], answer: 0, explain: "The investigation graph maps an incident's entities and relationships so analysts can explore scope and impact." },
  { cat: "sentinel", topic: "s_incidents", q: "After resolving an incident that was a genuine attack, how should an analyst close it to improve future ML and reporting?", options: ["Set status to Closed with classification True Positive", "Delete the workspace", "Leave it open indefinitely", "Disable the analytics rule"], answer: 0, explain: "Closing incidents with an accurate classification (e.g., True Positive) improves reporting and tuning of detections." },
  { cat: "sentinel", topic: "s_incidents", q: "A tier-1 analyst needs to add a saved hunting result to an active incident as supporting evidence. What can they attach?", options: ["A bookmark", "A DCR", "A commitment tier", "An ASR rule"], answer: 0, explain: "Bookmarks (saved hunting findings) can be added to incidents as evidence during investigation." },

  /* --- KQL --- */
  { cat: "sentinel", topic: "s_kql", q: "Which KQL operator filters rows based on a condition?", options: ["where", "project", "summarize", "render"], answer: 0, explain: "where filters rows by a boolean condition (e.g., | where TimeGenerated > ago(1d))." },
  { cat: "sentinel", topic: "s_kql", q: "An analyst wants to count sign-in events grouped by user account. Which KQL operator performs this aggregation?", options: ["summarize count() by UserPrincipalName", "project UserPrincipalName", "where UserPrincipalName != ''", "take 10"], answer: 0, explain: "summarize aggregates rows into groups; summarize count() by UserPrincipalName counts events per user." },
  { cat: "sentinel", topic: "s_kql", q: "In KQL, which operator ADDS a new calculated column while keeping the existing columns?", options: ["extend", "project", "distinct", "where"], answer: 0, explain: "extend adds a computed column; project selects/renames a subset of columns (dropping the rest)." },
  { cat: "sentinel", topic: "s_kql", q: "Which KQL expression returns records from the last 24 hours?", options: ["| where TimeGenerated > ago(1d)", "| take 24", "| project TimeGenerated", "| summarize by TimeGenerated"], answer: 0, explain: "ago(1d) yields the time 24 hours ago; combined with where TimeGenerated > ago(1d) it filters to the last day." },
  { cat: "sentinel", topic: "s_kql", q: "An analyst needs to combine rows from two different tables (e.g., SigninLogs and AuditLogs) into one result set. Which KQL operator stacks tables together?", options: ["union", "join", "summarize", "parse"], answer: 0, explain: "union combines rows from multiple tables into one set; join merges rows on a matching key instead." },
  { cat: "sentinel", topic: "s_kql", q: "Which KQL operator returns the top 5 devices by event count, highest first?", options: ["top 5 by Count desc", "take 5", "limit 5", "distinct DeviceName"], answer: 0, explain: "top N by Column returns the N highest (or lowest) rows by a value; take/limit just returns an arbitrary N rows." },

];
